// Command iconset regenerates markdown/icons/vendored.svg, the icons
// callable as <gno-icon name="..." />, from the names listed in
// markdown/icons/icons.txt. It downloads the pinned upstream archive, so the
// output depends only on the list and the pin.
//
// Run with `make icons`, which passes the gnoweb directory as the only
// argument.
package main

import (
	"archive/tar"
	"bufio"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// The upstream set is System UIcons, released into the public domain under
// the Unlicense. Bump the commit to pick up upstream changes.
const (
	upstreamArchive = "https://codeload.github.com/CoreyGinnivan/system-uicons/tar.gz/"
	upstreamCommit  = "4a17b006f9f3a6f549631d408daae322737be366"
	upstreamDir     = "src/images/icons/"

	// The upstream icons are drawn with a 1px stroke on a 21px grid; 1.3
	// gives them the stroke weight the gnoweb chrome icons have on their
	// 24px grid (1.5), so both families look alike at the same size.
	strokeWidth = "1.3"
	viewBox     = "0 0 21 21"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: iconset <gnoweb dir>")
		os.Exit(2)
	}
	dir := filepath.Join(os.Args[1], "markdown", "icons")
	if err := run(filepath.Join(dir, "icons.txt"), filepath.Join(dir, "vendored.svg")); err != nil {
		fmt.Fprintln(os.Stderr, "iconset:", err)
		os.Exit(1)
	}
}

type entry struct{ name, file string }

// run writes the vendored set. A name the chrome or drawn icons already use
// fails TestIconTable, which `make icons` runs next to build the icon table.
func run(listPath, outPath string) error {
	entries, err := readList(listPath)
	if err != nil {
		return err
	}

	icons, err := fetchUpstream()
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString("<svg xmlns=\"http://www.w3.org/2000/svg\">\n")
	buf.WriteString("<!-- Generated by `make icons` from icons.txt. DO NOT EDIT. -->\n")
	listed := map[string]bool{}
	for _, e := range entries {
		if listed[e.name] {
			return fmt.Errorf("%q: listed twice", e.name)
		}
		listed[e.name] = true

		src, ok := icons[e.file]
		if !ok {
			return fmt.Errorf("%q: no upstream icon %q", e.name, e.file)
		}
		body, err := svgBody(src)
		if err != nil {
			return fmt.Errorf("%q: %w", e.name, err)
		}
		fmt.Fprintf(&buf, "<symbol id=\"ico-%s\" viewBox=%q stroke-width=%q>%s</symbol>\n", e.name, viewBox, strokeWidth, body)
	}
	buf.WriteString("</svg>\n")

	return os.WriteFile(outPath, buf.Bytes(), 0o644)
}

// readList parses icons.txt: one `name [upstream_file]` per line, `#`
// comments and blank lines ignored.
func readList(p string) ([]entry, error) {
	f, err := os.Open(p)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []entry
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) == 0 || strings.HasPrefix(fields[0], "#") {
			continue
		}
		e := entry{name: fields[0], file: strings.ReplaceAll(fields[0], "-", "_")}
		switch len(fields) {
		case 1:
		case 2:
			e.file = fields[1]
		default:
			return nil, fmt.Errorf("%s: malformed line %q", p, sc.Text())
		}
		entries = append(entries, e)
	}
	return entries, sc.Err()
}

// fetchUpstream returns the upstream icons keyed by file name, without the
// .svg extension.
func fetchUpstream() (map[string][]byte, error) {
	resp, err := http.Get(upstreamArchive + upstreamCommit)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download: %s", resp.Status)
	}

	gz, err := gzip.NewReader(resp.Body)
	if err != nil {
		return nil, err
	}

	icons := map[string][]byte{}
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return icons, nil
		}
		if err != nil {
			return nil, err
		}
		// Archive entries are prefixed with "<repo>-<commit>/".
		_, name, _ := strings.Cut(hdr.Name, "/")
		if path.Dir(name)+"/" != upstreamDir || path.Ext(name) != ".svg" {
			continue
		}
		data, err := io.ReadAll(tr)
		if err != nil {
			return nil, err
		}
		icons[strings.TrimSuffix(path.Base(name), ".svg")] = data
	}
}

// svgBody returns the markup inside the root <svg> element, on one line.
// The table generator (markdown/ext_icons_gen_test.go) re-parses it against
// an element and attribute allowlist, so this only has to strip the wrapper.
func svgBody(src []byte) (string, error) {
	s := string(src)
	start := strings.Index(s, "<svg")
	if start < 0 {
		return "", fmt.Errorf("no <svg> element")
	}
	open := strings.IndexByte(s[start:], '>')
	end := strings.LastIndex(s, "</svg>")
	if open < 0 || end < start+open {
		return "", fmt.Errorf("malformed <svg> element")
	}
	return strings.Join(strings.Fields(s[start+open+1:end]), " "), nil
}
