on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61 # do not forget to change the version also on the makefile
          args:
            --config=./.github/golangci.yaml
