syntax = "proto3";
package bank;

option go_package = "github.com/gnolang/gno/tm2/pkg/sdk/bank/pb";

// imports
import "github.com/gnolang/gno/tm2/pkg/bft/abci/types/abci.proto";
import "github.com/gnolang/gno/tm2/pkg/crypto/merkle/merkle.proto";

// messages
message NoInputsError {
}

message NoOutputsError {
}

message InputOutputMismatchError {
}

message Input {
	string address = 1;
	string coins = 2;
}

message Output {
	string address = 1;
	string coins = 2;
}

message MsgSend {
	string from_address = 1;
	string to_address = 2;
	string amount = 3;
}

message GenesisState {
	Params params = 1;
}

message Params {
	repeated string restricted_denoms = 1;
}

message TransferEvent {
	string from = 1;
	string to = 2;
	string coins = 3;
}

message MultiTransferEvent {
	repeated Input inputs = 1;
	repeated Output outputs = 2;
}