// Code generated by genproto2; DO NOT EDIT.

package bank

import (
	"errors"
	"fmt"
	"reflect"

	"github.com/gnolang/gno/tm2/pkg/amino"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ reflect.Type

func init() {
	amino.RegisterGenproto2Type(reflect.TypeOf((*NoInputsError)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*NoOutputsError)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*InputOutputMismatchError)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*MsgSend)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*GenesisState)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*Params)(nil)).Elem())
}

func (goo NoInputsError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo NoInputsError) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	return s, nil
}

func (goo *NoInputsError) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = NoInputsError{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			return fmt.Errorf("unknown field number %d for NoInputsError", fnum)
		}
	}
	return nil
}

func (goo NoOutputsError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo NoOutputsError) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	return s, nil
}

func (goo *NoOutputsError) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = NoOutputsError{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			return fmt.Errorf("unknown field number %d for NoOutputsError", fnum)
		}
	}
	return nil
}

func (goo InputOutputMismatchError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo InputOutputMismatchError) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	return s, nil
}

func (goo *InputOutputMismatchError) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = InputOutputMismatchError{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			return fmt.Errorf("unknown field number %d for InputOutputMismatchError", fnum)
		}
	}
	return nil
}

func (goo MsgSend) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		repr, err := goo.Amount.MarshalAmino()
		if err != nil {
			return offset, err
		}
		if repr != "" {
			{
				before := offset
				offset = amino.PrependString(buf, offset, string(repr))
				valueLen := before - offset
				if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
					offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
				} else {
					offset = before
				}
			}
		}
	}
	{
		repr, err := goo.ToAddress.MarshalAmino()
		if err != nil {
			return offset, err
		}
		if repr != "" {
			{
				before := offset
				offset = amino.PrependString(buf, offset, string(repr))
				valueLen := before - offset
				if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
					offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
				} else {
					offset = before
				}
			}
		}
	}
	{
		repr, err := goo.FromAddress.MarshalAmino()
		if err != nil {
			return offset, err
		}
		if repr != "" {
			{
				before := offset
				offset = amino.PrependString(buf, offset, string(repr))
				valueLen := before - offset
				if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
					offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
				} else {
					offset = before
				}
			}
		}
	}
	return offset, err
}

func (goo MsgSend) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	{
		repr, err := goo.FromAddress.MarshalAmino()
		if err != nil {
			return 0, err
		}
		if repr != "" {
			s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
		}
	}
	{
		repr, err := goo.ToAddress.MarshalAmino()
		if err != nil {
			return 0, err
		}
		if repr != "" {
			s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
		}
	}
	{
		repr, err := goo.Amount.MarshalAmino()
		if err != nil {
			return 0, err
		}
		if repr != "" {
			s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
		}
	}
	return s, nil
}

func (goo *MsgSend) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = MsgSend{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.FromAddress.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.ToAddress.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 3:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Amount.UnmarshalAmino(repr); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unknown field number %d for MsgSend", fnum)
		}
	}
	return nil
}

func (goo GenesisState) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.Params.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo GenesisState) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	{
		cs, err := goo.Params.SizeBinary2(cdc)
		if err != nil {
			return 0, err
		}
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s, nil
}

func (goo *GenesisState) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = GenesisState{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Params.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unknown field number %d for GenesisState", fnum)
		}
	}
	return nil
}

func (goo Params) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.RestrictedDenoms) - 1; i >= 0; i-- {
		elem := goo.RestrictedDenoms[i]
		if elem != "" {
			offset = amino.PrependString(buf, offset, string(elem))
		} else {
			offset = amino.PrependByte(buf, offset, 0x00)
		}
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo Params) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	for _, elem := range goo.RestrictedDenoms {
		vs := amino.UvarintSize(uint64(len(elem))) + len(elem)
		s += 1 + vs
	}
	return s, nil
}

func (goo *Params) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = Params{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var ev string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			ev = string(v)
			goo.RestrictedDenoms = append(goo.RestrictedDenoms, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				var nextTyp3 amino.Typ3
				nextFnum, nextTyp3, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				if nextTyp3 != amino.Typ3ByteLength {
					return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, nextTyp3)
				}
				bz = bz[n:]
				var ev string
				v, n, err := amino.DecodeString(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				ev = string(v)
				goo.RestrictedDenoms = append(goo.RestrictedDenoms, ev)
			}
		default:
			return fmt.Errorf("unknown field number %d for Params", fnum)
		}
	}
	return nil
}
