version: 3

# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

project:
  id: github.com/gnolang/gno
  name: gno

targets:
  only:
    - type: gomod

paths:
  exclude:
    - ./misc/
