codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

comment:
  require_changes: true

coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 10
        informational: true
      - type: patch
        target: auto
        threshold: 10
        informational: true

ignore:
  - "tm2/pkg/db/mockdb"
  - "tm2/pkg/db/internal/test_common.go"
  - "gnovm/stdlibs/generated.go"
  - "gnovm/tests/stdlibs/generated.go"
  - "**/*.pb.go"
