codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

comment:
  require_changes: true

coverage:
  round: down
  precision: 2
  status:
    patch: # new lines
      default:
        target: 80
        threshold: 10
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true # Only check patch coverage on PRs

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 10 # Let's decrease this later.
      - type: patch
        target: auto # Let's decrease this later.
        threshold: 10

ignore:
  - "tm2/pkg/db/mockdb"
  - "tm2/pkg/db/internal/test_common.go"
  - "gnovm/stdlibs/generated.go"
  - "gnovm/tests/stdlibs/generated.go"
  - "**/*.pb.go"
