codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

comment:
  require_changes: true

coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 5 # Let's decrease this later.
        base: parent
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 5 # Let's decrease this later.
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true # Only check patch coverage on PRs

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 10 # Let's decrease this later.
      - type: patch
        target: auto # Let's decrease this later.
        threshold: 10

  groups:
    gno-land:
      paths:
        - "gno.land/**"
    gnovm:
      paths:
        - "gnovm/**"
    misc:
      paths:
        - "misc/**"
    tm2:
      paths:
        - "tm2/**"
    contribs:
      paths:
        - "contribs/**"

  statuses:
    - type: project
      flag: gno.land
      target: auto
      threshold: 5
    - type: project
      flag: gnovm
      target: auto
      threshold: 2 # Stricter threshold
    - type: project
      flag: misc
      target: auto
      threshold: 10
    - type: project
      flag: tm2
      target: auto
      threshold: 5
    - type: project
      flag: contribs
      target: auto
      threshold: 5

ignore:
  - "gnovm/stdlibs/generated.go"
  - "gnovm/tests/stdlibs/generated.go"
  - "**/*.pb.go"
