codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

ignore:
  - misc

comment:
  require_changes: false

coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 1%

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.5%
      - type: patch
        target: auto
        threshold: 1%
  individual_flags:
    - name: tm2
      paths:
      - tm2
    - name: gnovm
      paths:
      - gnovm
    - name: gno.land
      paths:
      - gno.land
