codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

ignore:
  - misc

comment: false # will use it later.

flags:
  default_rules:
    carryforward: true
  tm2:
    paths:
      - tm2
    after_n_builds: 4
