codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

ignore:
  - misc

comment:
  layout: "header, diff, flags, components"
  require_changes: true

coverage:
  #range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        #informational: true
    patch:
      default:
        target: auto

component_management:
  individual_components:
    - component_id: tm2
      name: tm2
      paths:
        - tm2
    - component_id: gnovm
      name: gnovm
      paths:
        - gnovm
    - component_id: gno.land
      name: gno.land
      paths:
        - gno.land
