codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

ignore:
  - misc

comment:
  require_changes: true

coverage:
  #range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        #informational: true
    patch:
      default:
        target: auto

flags:
  default_rules:
    carryforward: true
  tm2:
    paths:
      - tm2
    after_n_builds: 4
  gnovm:
    paths:
      - gnovm
    after_n_builds: 9
  gno.land:
    paths:
      - gno.land
    after_n_builds: 3
