codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

comment:
  require_changes: false

coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 10 # Let's decrease this later.
        base: parent
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 10 # Let's decrease this later.
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 10 # Let's decrease this later.
      - type: patch
        target: auto # Let's decrease this later.
        threshold: 10
