codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

ignore:
  - misc

comment:
  require_changes: false

coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 10 # Let's decrease this later.
        base: parent
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 100 # Allows PRs without tests, overall stats count.
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 10 # Let's decrease this later.
      - type: patch
        target: auto # Allows PRs without tests, overall stats count.
        threshold: 100
  individual_flags:
    - name: tm2
      paths:
      - tm2
    - name: gnovm
      paths:
      - gnovm
    - name: gno.land
      paths:
      - gno.land
    - name: misc
      paths:
      - misc
