project_name: gno

before:
  hooks:
    - go mod tidy

builds:
  - id: gno
    main: ./gnovm/cmd/gno
    binary: gno
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
  - id: gnoland
    main: ./gno.land/cmd/gnoland
    binary: gnoland
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
  - id: gnokey
    main: ./gno.land/cmd/gnokey
    binary: gnokey
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
  - id: gnoweb
    main: ./gno.land/cmd/gnoweb
    binary: gnoweb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
gomod:
  proxy: true

archives:
  # https://goreleaser.com/customization/archive/
  - files:
      # Standard Release Files
      - LICENSE.md
      - README.md

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true
checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append
  footer: |
    ### Container Images

    You can find all docker images at:

    https://github.com/orgs/gnolang/packages?repo_name={{ .ProjectName }}

nightly:
  tag_name: nightly
  publish_release: true
  keep_single_release: true
