FROM busybox

COPY ./gno /gno
COPY ./examples /gnoroot/examples/
COPY ./gnovm/stdlibs /gnoroot/gnovm/stdlibs/
COPY ./gnovm/tests/stdlibs /gnoroot/gnovm/tests/stdlibs/

ENV GNOROOT="/gnoroot/"

ENTRYPOINT [ "/gno" ]
CMD [ "" ]