FROM busybox

COPY ./gno /usr/bin/gno
COPY ./examples /gnoroot/examples/
COPY ./gnovm/stdlibs /gnoroot/gnovm/stdlibs/
COPY ./gnovm/tests/stdlibs /gnoroot/gnovm/tests/stdlibs/

ENV GNOROOT="/gnoroot/"

WORKDIR /gnoroot/

ENTRYPOINT [ "/usr/bin/gno" ]

CMD [ "" ]
