FROM busybox

COPY ./gnoland /usr/bin/gnoland
COPY ./examples /gnoroot/examples/
COPY ./gnovm/stdlibs /gnoroot/gnovm/stdlibs/
COPY ./gno.land/genesis/genesis_balances.txt /gnoroot/gno.land/genesis/genesis_balances.txt
COPY ./gno.land/genesis/genesis_txs.jsonl /gnoroot/gno.land/genesis/genesis_txs.jsonl

ENV GNOROOT="/gnoroot/"

WORKDIR /gnoroot/
EXPOSE 26656 26657
ENTRYPOINT [ "/gnoland" ]
CMD [ "" ]
