// Code generated by genproto2. DO NOT EDIT.

package consensus

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"github.com/gnolang/gno/tm2/pkg/bitarray"
	"bytes"
	"github.com/gnolang/gno/tm2/pkg/crypto"
	cstypes "github.com/gnolang/gno/tm2/pkg/bft/consensus/types"
	"errors"
	"fmt"
	"io"
	"time"
	"github.com/gnolang/gno/tm2/pkg/bft/types"
)

var _ io.Writer
var _ fmt.Stringer
var _ *amino.Codec
var _ bytes.Buffer
var _ = errors.New
var _ time.Time

func (goo NewRoundStepMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	if goo.Step != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeUvarint(w, uint64(goo.Step)); err != nil {
			return err
		}
	}
	if goo.SecondsSinceStartTime != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.SecondsSinceStartTime)); err != nil {
			return err
		}
	}
	if goo.LastCommitRound != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 5, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.LastCommitRound)); err != nil {
			return err
		}
	}
	return nil
}

func (goo NewRoundStepMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.Step != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Step))
	}
	if goo.SecondsSinceStartTime != 0 {
		s += 1 + amino.VarintSize(int64(goo.SecondsSinceStartTime))
	}
	if goo.LastCommitRound != 0 {
		s += 1 + amino.VarintSize(int64(goo.LastCommitRound))
	}
	return s
}

func (goo *NewRoundStepMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 3:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Step = cstypes.RoundStepType(v)
		case 4:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.SecondsSinceStartTime = int(v)
		case 5:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.LastCommitRound = int(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo NewValidBlockMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	{
		var buf bytes.Buffer
		if err := goo.BlockPartsHeader.MarshalBinary2(cdc, &buf); err != nil {
			return err
		}
		bz := buf.Bytes()
		if len(bz) == 0 || (len(bz) == 1 && bz[0] == 0x00) {
			// skip empty
		} else {
			if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	if goo.BlockParts != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.BlockParts).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	if goo.IsCommit {
		if err := amino.EncodeFieldNumberAndTyp3(w, 5, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeBool(w, bool(goo.IsCommit)); err != nil {
			return err
		}
	}
	return nil
}

func (goo NewValidBlockMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	{
		cs := goo.BlockPartsHeader.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.BlockParts != nil {
		{
			cs := (*goo.BlockParts).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.IsCommit {
		s += 1 + 1
	}
	return s
}

func (goo *NewValidBlockMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 3:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockPartsHeader.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 4:
			{
				var pv bitarray.BitArray
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.BlockParts = &pv
			}
		case 5:
			v, n, err := amino.DecodeBool(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.IsCommit = bool(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo ProposalMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Proposal != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Proposal).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo ProposalMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Proposal != nil {
		{
			cs := (*goo.Proposal).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *ProposalMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			{
				var pv types.Proposal
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Proposal = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo ProposalPOLMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.ProposalPOLRound != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.ProposalPOLRound)); err != nil {
			return err
		}
	}
	if goo.ProposalPOL != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.ProposalPOL).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo ProposalPOLMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.ProposalPOLRound != 0 {
		s += 1 + amino.VarintSize(int64(goo.ProposalPOLRound))
	}
	if goo.ProposalPOL != nil {
		{
			cs := (*goo.ProposalPOL).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *ProposalPOLMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.ProposalPOLRound = int(v)
		case 3:
			{
				var pv bitarray.BitArray
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.ProposalPOL = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo BlockPartMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	if goo.Part != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Part).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo BlockPartMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.Part != nil {
		{
			cs := (*goo.Part).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *BlockPartMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 3:
			{
				var pv types.Part
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Part = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo VoteMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Vote != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Vote).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo VoteMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Vote != nil {
		{
			cs := (*goo.Vote).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *VoteMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			{
				var pv types.Vote
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Vote = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo HasVoteMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	if goo.Type != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeUvarint(w, uint64(goo.Type)); err != nil {
			return err
		}
	}
	if goo.Index != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Index)); err != nil {
			return err
		}
	}
	return nil
}

func (goo HasVoteMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.Type != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Type))
	}
	if goo.Index != 0 {
		s += 1 + amino.VarintSize(int64(goo.Index))
	}
	return s
}

func (goo *HasVoteMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 3:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = types.SignedMsgType(v)
		case 4:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Index = int(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo VoteSetMaj23Message) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	if goo.Type != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeUvarint(w, uint64(goo.Type)); err != nil {
			return err
		}
	}
	{
		var buf bytes.Buffer
		if err := goo.BlockID.MarshalBinary2(cdc, &buf); err != nil {
			return err
		}
		bz := buf.Bytes()
		if len(bz) == 0 || (len(bz) == 1 && bz[0] == 0x00) {
			// skip empty
		} else {
			if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo VoteSetMaj23Message) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.Type != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Type))
	}
	{
		cs := goo.BlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *VoteSetMaj23Message) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 3:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = types.SignedMsgType(v)
		case 4:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo VoteSetBitsMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	if goo.Type != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeUvarint(w, uint64(goo.Type)); err != nil {
			return err
		}
	}
	{
		var buf bytes.Buffer
		if err := goo.BlockID.MarshalBinary2(cdc, &buf); err != nil {
			return err
		}
		bz := buf.Bytes()
		if len(bz) == 0 || (len(bz) == 1 && bz[0] == 0x00) {
			// skip empty
		} else {
			if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	if goo.Votes != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Votes).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 5, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo VoteSetBitsMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.Type != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Type))
	}
	{
		cs := goo.BlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Votes != nil {
		{
			cs := (*goo.Votes).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *VoteSetBitsMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 3:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = types.SignedMsgType(v)
		case 4:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 5:
			{
				var pv bitarray.BitArray
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Votes = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo newRoundStepInfo) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	{
		var buf bytes.Buffer
		if err := goo.HRS.MarshalBinary2(cdc, &buf); err != nil {
			return err
		}
		bz := buf.Bytes()
		if len(bz) == 0 || (len(bz) == 1 && bz[0] == 0x00) {
			// skip empty
		} else {
			if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo newRoundStepInfo) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.HRS.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *newRoundStepInfo) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.HRS.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo msgInfo) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Msg != nil {
		if goo.Msg != nil {
			anyBz, err := cdc.MarshalAny(goo.Msg)
			if err != nil {
				return err
			}
			if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, anyBz); err != nil {
				return err
			}
		}
	}
	if goo.PeerID != "" {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeString(w, string(goo.PeerID)); err != nil {
			return err
		}
	}
	return nil
}

func (goo msgInfo) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Msg != nil {
		if goo.Msg != nil {
			anyBz, err := cdc.MarshalAny(goo.Msg)
			if err != nil {
				panic(err)
			}
			s += 1 + amino.UvarintSize(uint64(len(anyBz))) + len(anyBz)
		}
	}
	if goo.PeerID != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.PeerID))) + len(goo.PeerID)
	}
	return s
}

func (goo *msgInfo) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(fbz) > 0 {
				if err := cdc.UnmarshalAny(fbz, &goo.Msg); err != nil {
					return err
				}
			}
		case 2:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.PeerID = crypto.ID(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo timeoutInfo) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	{
		var buf bytes.Buffer
		if err := amino.EncodeDuration(&buf, goo.Duration); err != nil {
			return err
		}
		bz := buf.Bytes()
		if len(bz) == 0 || (len(bz) == 1 && bz[0] == 0x00) {
			// skip empty
		} else {
			if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	if goo.Height != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Height)); err != nil {
			return err
		}
	}
	if goo.Round != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Round)); err != nil {
			return err
		}
	}
	if goo.Step != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeUvarint(w, uint64(goo.Step)); err != nil {
			return err
		}
	}
	return nil
}

func (goo timeoutInfo) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := amino.DurationSize(goo.Duration)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.Step != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Step))
	}
	return s
}

func (goo *timeoutInfo) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			// time.Duration (ByteLength)
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Duration, _, err = amino.DecodeDuration(fbz)
			if err != nil {
				return err
			}
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 3:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 4:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Step = cstypes.RoundStepType(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

