package main

import (
	"context"
	"os"

	"github.com/gnolang/gno/tm2/pkg/amino"
	"github.com/gnolang/gno/tm2/pkg/amino/genproto"
	"github.com/gnolang/gno/tm2/pkg/amino/tests"
	"github.com/gnolang/gno/tm2/pkg/commands"
)

func main() {
	cmd := commands.NewCommand(
		commands.Metadata{
			LongHelp: "Generates proto bindings for amino's test types (pbbindings.go) " +
				"used by the 3-way fuzz oracle. Production .proto and pb3_gen.go " +
				"are generated by misc/genproto2.",
		},
		commands.NewEmptyConfig(),
		execGen,
	)

	cmd.Execute(context.Background(), os.Args[1:])
}

func execGen(_ context.Context, _ []string) error {
	// Only tests.Package is kept here: _testCodec in reflect_test.go type-
	// asserts amino.PBMessager on fuzzed values, which requires a generated
	// pbbindings.go alongside the types. All other packages are served by
	// misc/genproto2, which owns canonical .proto + pb3_gen.go emission.
	pkgs := []*amino.Package{
		tests.Package,
	}

	for _, pkg := range pkgs {
		genproto.WriteProto3Schema(pkg)
		genproto.WriteProtoBindings(pkg)
		genproto.MakeProtoFolder(pkg, "proto")
	}

	for _, pkg := range pkgs {
		genproto.RunProtoc(pkg, "proto")
	}

	return nil
}
