#!/usr/bin/env bash
# Regenerates MIGRATION.md — a ledger of the Go-corpus files migrated under
# testdata/, bucketed by priority (real Gno bugs first) with links to each
# file. Run from this directory:  ./gen_ledger.sh
#
# A KnownIssue is any Gno bug. Urgency is DERIVED here from the pinned facts,
# not stored in the file:
#   - 🔥 URGENT: run-mode KnownIssue (file pins // GnoOutput:) — a RUNTIME
#     divergence: Gno's run result differs from Go's (a wrong value, or a
#     panic where Go succeeds, e.g. bug446). These ship past the deploy gate
#     and break/misbehave in production -> fix now.
#   - 🟠 DEFERRED: static KnownIssue (no run-mode facts) — Gno preprocess
#     rejects code gc + go/types accept. Caught at deploy (can't ship); no
#     inconsistent state -> defer.
# (Precise sub-triage of the urgent set — engine panic vs semantic bug vs
# misrouted feature-gap — is done by reading each file's pinned behavior;
# not auto-bucketed here.)
# Other buckets are not bugs: KnownDivergence (accepted run-mode difference),
# Unsupported (feature gap, skipped), GnoStaticIncomplete (partial errorcheck
# marker coverage — a caveat), Clean.
#
# Bucket priority (a file lands in its highest bucket):
#   urgent > deferred > KnownDivergence > Unsupported > Clean
# (GnoStaticIncomplete is a caveat that rides along; it only decides the
# bucket when it's the sole tag, ranking just above Unsupported.)
set -euo pipefail
cd "$(dirname "$0")"
root=testdata
out=MIGRATION.md

# Collect files per bucket (highest priority wins).
declare -a urgent uncaught deferred divergence incomplete guardonly unsupported clean
note_of() { # $1=file $2=directive -> inline content, else first content line
  awk -v d="$2" '
    index($0, "// " d ":") == 1 {
      rest = $0; sub("^// " d ": *", "", rest)
      if (rest != "") { print rest; exit }   # single-line: content after colon
      p = 1; next                              # multi-line: take next // line
    }
    p && /^\/\// { sub(/^\/\/ ?/, ""); print; exit }
    p { exit }
  ' "$1"
}
status_of() { # $1=file -> triage status marker (✅ Fixed / 🚧 Fixing / 📌 Tracked), if any
  local f=$1 m c e
  for m in Fixed Fixing Tracked; do
    c=$(awk -v d="$m" 'index($0, "// " d ":") == 1 { rest = $0; sub("^// " d ": *", "", rest); print rest; exit }' "$f")
    if [ -n "$c" ]; then
      case $m in Fixed) e="✅";; Fixing) e="🚧";; Tracked) e="📌";; esac
      printf '%s %s: %s' "$e" "$m" "$c"; return
    fi
  done
}
for f in $(find "$root" -name '*.go' -o -name '*.gno' | sort); do
  if grep -q '^// UncaughtError:' "$f"; then uncaught+=("$f")
  elif grep -qE '^// (KnownIssue|GnoOverStrictError):' "$f"; then
    # Urgency derived: run-mode KnownIssue (pins // GnoOutput:) is a runtime
    # divergence (urgent); a static over-strict reject — compile-mode
    # KnownIssue or errorcheck GnoOverStrictError (derived set-relation
    # verdict: Gno rejects lines outside markers ∪ go/types) — is deferred.
    if grep -q '^// GnoOutput:' "$f"; then urgent+=("$f"); else deferred+=("$f"); fi
  elif grep -q '^// KnownDivergence:' "$f"; then divergence+=("$f")
  elif grep -q '^// GnoStaticIncomplete:' "$f"; then incomplete+=("$f")  # legacy; should be empty
  elif grep -q '^// Unsupported:' "$f"; then unsupported+=("$f")
  # Guard-only: go/types catches everything, Gno preprocess flags nothing
  # (an empty Gno catch is synced as NO GnoError/GnoPreprocessError block,
  # so absence here means "lenient", not "not synced"). Distinct from
  # GnoStaticIncomplete (partial coverage): rejection contract holds in
  # production via the guard, but is the native-coverage worklist for the
  # go/types removal plan.
  elif grep -q '^// GoTypeCheckError:' "$f" && \
       ! grep -qE '^// (GnoError|GnoPreprocessError):' "$f"; then guardonly+=("$f")
  else clean+=("$f"); fi
done

total=$(find "$root" -name '*.go' -o -name '*.gno' | wc -l | tr -d ' ')
emit_section() { # $1=title $2=blurb $3=directive(for note) $4..=files
  local title=$1 blurb=$2 directive=$3; shift 3
  printf '\n## %s (%d)\n\n%s\n\n' "$title" "$#" "$blurb" >>"$out"
  [ "$#" -eq 0 ] && { printf '_none_\n' >>"$out"; return; }
  for f in "$@"; do
    local note="" status="" d
    for d in $directive; do  # space-separated fallback list
      note=$(note_of "$f" "$d")
      [ -n "$note" ] && break
    done
    status=$(status_of "$f")
    printf -- '- [`%s`](%s)' "${f#testdata/}" "$f" >>"$out"
    [ -n "$note" ] && printf -- ' — %s' "$note" >>"$out"
    [ -n "$status" ] && printf -- ' — %s' "$status" >>"$out"
    printf '\n' >>"$out"
  done
}

{
  echo "# Go-corpus migration ledger"
  echo
  echo "Files under \`testdata/\` lifted from Go's standard test corpus, run"
  echo "through the GnoVM filetest harness. Auto-generated by \`gen_ledger.sh\` —"
  echo "do not edit by hand; re-run after \`--update-golden-tests\`."
  echo
  echo "## Totals"
  echo
  echo "| Bucket | Count | Meaning |"
  echo "|---|--:|---|"
  echo "| 🔥 **Urgent KnownIssue** | ${#urgent[@]} | runtime divergence — Gno's run result differs from Go's (wrong value, or panic where Go succeeds); ships past deploy, breaks in production; **fix now** |"
  echo "| 🕳️ **Uncaught leak** | ${#uncaught[@]} | gc-invalid code caught by NEITHER Gno preprocess nor go/types — would deploy; under-rejection, **fix now** |"
  echo "| 🟠 **Over-strict** | ${#deferred[@]} | Gno rejects code gc *and* go/types accept (static; caught at deploy, no inconsistent state — fix deferred) |"
  echo "| 🔵 KnownDivergence | ${#divergence[@]} | accepted run-mode difference (not a bug) |"
  echo "| 🛡️ Permissive-GuardOnly | ${#guardonly[@]} | Gno preprocess accepts; the go/types guard alone rejects — holds in production, but is the native-coverage worklist for go/types removal |"
  echo "| ⚪ Unsupported | ${#unsupported[@]} | feature gap (unsupported import / language feature); skipped |"
  echo "| ✅ Clean | ${#clean[@]} | verified, no outstanding issue |"
  echo "| **Total migrated** | ${total} | |"
} >"$out"
if [ "${#incomplete[@]:-0}" -gt 0 ]; then
  echo "⚠ ${#incomplete[@]} files still carry legacy // GnoStaticIncomplete: — re-sync them" >>"$out"
fi

emit_section "🔥 Urgent KnownIssue — runtime divergence (fix now)" \
  "Gno's run-mode result differs from Go's — a wrong value, or a panic where Go succeeds (e.g. bug446: init-order panic). Unlike static rejects (caught at deploy), these ship and break in production, so they're the must-fix subset. Read each file's pinned // GnoOutput:/// GnoError: vs // GoOutput: to identify the bug. Many files share a root cause; sub-triage (engine panic vs semantic bug vs misrouted feature-gap) is done by reading the behavior." \
  KnownIssue ${urgent[@]+"${urgent[@]}"}
emit_section "🕳️ Uncaught leak — gc-invalid code deploys" \
  "Checkable (non-GC_ERROR) markers caught by neither Gno's preprocess nor the go/types guard: the whole stack accepts code gc rejects. Under-rejection — invalid packages deploy — so these rank with (arguably above) the urgent bucket." \
  UncaughtError ${uncaught[@]+"${uncaught[@]}"}
emit_section "🟠 Over-strict — Gno-only static rejects (fix deferred)" \
  "Gno's preprocess rejects code that both gc (markers) and the go/types guard accept. Only over-rejects otherwise-valid packages (they can't deploy/call) — no inconsistent state — so deferred. Note = human verdict (compile KnownIssue) or the first over-strict line (errorcheck GnoOverStrictError)." \
  "KnownIssue GnoOverStrictError" ${deferred[@]+"${deferred[@]}"}
emit_section "🔵 KnownDivergence — accepted run-mode differences" \
  "Gno's output legitimately differs from Go's (formatting, map order, error wording, …); pinned and blessed, not a bug." \
  KnownDivergence ${divergence[@]+"${divergence[@]}"}
emit_section "🛡️ Permissive-GuardOnly — Gno accepts, go/types alone rejects" \
  "Every gc marker is caught by the go/types guard and NONE by Gno's own preprocess (an empty Gno catch is synced as no GnoError block — absence means lenient, not unsynced). The rejection contract holds in production (guard runs at addpkg), but each file flips to silently-accepted the day the transitional guard is removed — this is the native type_check.go coverage worklist. Note shows the guard's first error." \
  GoTypeCheckError ${guardonly[@]+"${guardonly[@]}"}
emit_section "⚪ Unsupported — feature gaps (skipped)" \
  "Gno can't process the file (unsupported import or language feature). Skipped via t.Skip." \
  Unsupported ${unsupported[@]+"${unsupported[@]}"}
# Clean-section audit (standing invariants, re-derived each regen —
# hardened from the 2026-07 one-off audit that caught 15 run files never
# both-sides compared and 3 pragma-marker errorcheck files never checked):
#   - run:        must pin BOTH // GnoOutput: and // GoOutput: (content
#                 equality is enforced by the harness at test time)
#   - compile:    must have NO pins (all checkers accept)
#   - errorcheck: must have // GnoError: (else it belongs to GuardOnly)
# Violations are listed inline as ⚠ ANOMALY — a Clean bucket with
# anomalies is not clean.
clean_run_empty=0; clean_run_out=0; clean_ec=0; clean_compile=0; clean_other=0
declare -a clean_anomalies
for f in ${clean[@]+"${clean[@]}"}; do
  mode=$(head -1 "$f" | sed 's|^// ||;s/ .*//')
  case "$mode" in
    run)
      if ! grep -q '^// GnoOutput:' "$f" || ! grep -q '^// GoOutput:' "$f"; then
        clean_anomalies+=("$f — run-mode Clean but missing GnoOutput/GoOutput pins (never both-sides compared)")
      elif awk '/^\/\/ GoOutput:$/{p=1;next} p&&/^\/\/ /{n++;next} p{exit} END{exit n==0}' "$f"; then
        clean_run_out=$((clean_run_out+1))
      else
        clean_run_empty=$((clean_run_empty+1))
      fi ;;
    compile)
      if grep -qE '^// (GnoError|GnoOutput|GoOutput|GnoPreprocessError|GoBuildError|GoTypeCheckError):' "$f"; then
        clean_anomalies+=("$f — compile Clean but carries pins")
      else
        clean_compile=$((clean_compile+1))
      fi ;;
    errorcheck)
      if ! grep -q '^// GnoError:' "$f"; then
        clean_anomalies+=("$f — errorcheck Clean without GnoError (should be GuardOnly or Unsupported)")
      else
        clean_ec=$((clean_ec+1))
      fi ;;
    *) clean_other=$((clean_other+1)) ;;
  esac
done
clean_blurb="Gno's behavior is pinned and matches; no outstanding issue. Composition (invariants re-checked at each regen): ${clean_run_empty} run/both-silent, ${clean_run_out} run/matching-output, ${clean_ec} errorcheck/full-marker-coverage-with-Gno, ${clean_compile} compile/all-checkers-accept, ${clean_other} other modes."
if [ "${#clean_anomalies[@]}" -gt 0 ]; then
  clean_blurb="$clean_blurb
**⚠ ${#clean_anomalies[@]} ANOMALIES (unverified files counted Clean — fix the pins or the harness):**"
  for a in ${clean_anomalies[@]+"${clean_anomalies[@]}"}; do
    clean_blurb="$clean_blurb
- \`${a#testdata/}\`"
  done
fi
emit_section "✅ Clean — verified" \
  "$clean_blurb" \
  "" ${clean[@]+"${clean[@]}"}

echo "wrote $out ($total files)"
