// Code generated by genproto2; DO NOT EDIT.

package merkle

import (
	"errors"
	"fmt"
	"reflect"

	"github.com/gnolang/gno/tm2/pkg/amino"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ reflect.Type

func init() {
	amino.RegisterGenproto2Type(reflect.TypeOf((*ProofOp)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*Proof)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*SimpleProof)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*SimpleProofNode)(nil)).Elem())
}

func (goo ProofOp) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.Data) != 0 {
		{
			before := offset
			offset = amino.PrependByteSlice(buf, offset, goo.Data)
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
			} else {
				offset = before
			}
		}
	}
	if len(goo.Key) != 0 {
		{
			before := offset
			offset = amino.PrependByteSlice(buf, offset, goo.Key)
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
			} else {
				offset = before
			}
		}
	}
	if goo.Type != "" {
		{
			before := offset
			offset = amino.PrependString(buf, offset, string(goo.Type))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
			} else {
				offset = before
			}
		}
	}
	return offset, err
}

func (goo ProofOp) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Type != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.Type))) + len(goo.Type)
	}
	if len(goo.Key) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Key)
	}
	if len(goo.Data) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Data)
	}
	return s, nil
}

func (goo *ProofOp) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = ProofOp{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = string(v)
		case 2:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Key = nil
			} else {
				goo.Key = v
			}
		case 3:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Data = nil
			} else {
				goo.Data = v
			}
		default:
			return fmt.Errorf("unknown field number %d for ProofOp", fnum)
		}
	}
	return nil
}

func (goo Proof) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.Ops) - 1; i >= 0; i-- {
		elem := goo.Ops[i]
		before := offset
		offset, err = elem.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo Proof) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	for _, elem := range goo.Ops {
		cs, err := elem.SizeBinary2(cdc)
		if err != nil {
			return 0, err
		}
		s += 1 + amino.UvarintSize(uint64(cs)) + cs
	}
	return s, nil
}

func (goo *Proof) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = Proof{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var ev ProofOp
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := ev.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
				return err
			}
			goo.Ops = append(goo.Ops, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				var nextTyp3 amino.Typ3
				nextFnum, nextTyp3, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				if nextTyp3 != amino.Typ3ByteLength {
					return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, nextTyp3)
				}
				bz = bz[n:]
				var ev ProofOp
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := ev.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
					return err
				}
				goo.Ops = append(goo.Ops, ev)
			}
		default:
			return fmt.Errorf("unknown field number %d for Proof", fnum)
		}
	}
	return nil
}

func (goo SimpleProof) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.Aunts) - 1; i >= 0; i-- {
		elem := goo.Aunts[i]
		if len(elem) != 0 {
			offset = amino.PrependByteSlice(buf, offset, elem)
		} else {
			offset = amino.PrependByte(buf, offset, 0x00)
		}
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
	}
	if len(goo.LeafHash) != 0 {
		{
			before := offset
			offset = amino.PrependByteSlice(buf, offset, goo.LeafHash)
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
			} else {
				offset = before
			}
		}
	}
	if goo.Index != 0 {
		{
			before := offset
			offset = amino.PrependVarint(buf, offset, int64(goo.Index))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	if goo.Total != 0 {
		{
			before := offset
			offset = amino.PrependVarint(buf, offset, int64(goo.Total))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	return offset, err
}

func (goo SimpleProof) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Total != 0 {
		s += 1 + amino.VarintSize(int64(goo.Total))
	}
	if goo.Index != 0 {
		s += 1 + amino.VarintSize(int64(goo.Index))
	}
	if len(goo.LeafHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.LeafHash)
	}
	for _, elem := range goo.Aunts {
		vs := amino.ByteSliceSize(elem)
		s += 1 + vs
	}
	return s, nil
}

func (goo *SimpleProof) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = SimpleProof{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Total = int(v)
		case 2:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Index = int(v)
		case 3:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.LeafHash = nil
			} else {
				goo.LeafHash = v
			}
		case 4:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var ev []uint8
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				ev = nil
			} else {
				ev = v
			}
			goo.Aunts = append(goo.Aunts, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				var nextTyp3 amino.Typ3
				nextFnum, nextTyp3, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 4 {
					break
				}
				if nextTyp3 != amino.Typ3ByteLength {
					return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3ByteLength, nextTyp3)
				}
				bz = bz[n:]
				var ev []uint8
				v, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if len(v) == 0 {
					ev = nil
				} else {
					ev = v
				}
				goo.Aunts = append(goo.Aunts, ev)
			}
		default:
			return fmt.Errorf("unknown field number %d for SimpleProof", fnum)
		}
	}
	return nil
}

func (goo SimpleProofNode) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Right != nil {
		{
			before := offset
			offset, err = (*goo.Right).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
		}
	}
	if goo.Left != nil {
		{
			before := offset
			offset, err = (*goo.Left).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
		}
	}
	if goo.Parent != nil {
		{
			before := offset
			offset, err = (*goo.Parent).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if len(goo.Hash) != 0 {
		{
			before := offset
			offset = amino.PrependByteSlice(buf, offset, goo.Hash)
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
			} else {
				offset = before
			}
		}
	}
	return offset, err
}

func (goo SimpleProofNode) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if len(goo.Hash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Hash)
	}
	if goo.Parent != nil {
		{
			cs, err := (*goo.Parent).SizeBinary2(cdc)
			if err != nil {
				return 0, err
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Left != nil {
		{
			cs, err := (*goo.Left).SizeBinary2(cdc)
			if err != nil {
				return 0, err
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Right != nil {
		{
			cs, err := (*goo.Right).SizeBinary2(cdc)
			if err != nil {
				return 0, err
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s, nil
}

func (goo *SimpleProofNode) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = SimpleProofNode{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Hash = nil
			} else {
				goo.Hash = v
			}
		case 2:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			{
				var pv SimpleProofNode
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
					return err
				}
				goo.Parent = &pv
			}
		case 3:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			{
				var pv SimpleProofNode
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
					return err
				}
				goo.Left = &pv
			}
		case 4:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			{
				var pv SimpleProofNode
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
					return err
				}
				goo.Right = &pv
			}
		default:
			return fmt.Errorf("unknown field number %d for SimpleProofNode", fnum)
		}
	}
	return nil
}
