// Code generated by genproto2. DO NOT EDIT.

package merkle

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"bytes"
	"errors"
	"fmt"
	"io"
)

var _ io.Writer
var _ fmt.Stringer
var _ *amino.Codec
var _ bytes.Buffer
var _ = errors.New

func (goo ProofOp) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Type != "" {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeString(w, string(goo.Type)); err != nil {
			return err
		}
	}
	if len(goo.Key) != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, goo.Key); err != nil {
			return err
		}
	}
	if len(goo.Data) != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, goo.Data); err != nil {
			return err
		}
	}
	return nil
}

func (goo ProofOp) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Type != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.Type))) + len(goo.Type)
	}
	if len(goo.Key) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Key)
	}
	if len(goo.Data) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Data)
	}
	return s
}

func (goo *ProofOp) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = string(v)
		case 2:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Key = nil
			} else {
				goo.Key = v
			}
		case 3:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Data = nil
			} else {
				goo.Data = v
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Proof) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	for _, elem := range goo.Ops {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
			return err
		}
		var buf bytes.Buffer
		if err := elem.MarshalBinary2(cdc, &buf); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, buf.Bytes()); err != nil {
			return err
		}
	}
	return nil
}

func (goo Proof) SizeBinary2(cdc *amino.Codec) int {
	var s int
	for _, elem := range goo.Ops {
		cs := elem.SizeBinary2(cdc)
		s += 1 + amino.UvarintSize(uint64(cs)) + cs
	}
	return s
}

func (goo *Proof) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var ev ProofOp
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
			goo.Ops = append(goo.Ops, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				bz = bz[n:]
				var ev ProofOp
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Ops = append(goo.Ops, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo SimpleProof) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Total != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Total)); err != nil {
			return err
		}
	}
	if goo.Index != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Index)); err != nil {
			return err
		}
	}
	if len(goo.LeafHash) != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, goo.LeafHash); err != nil {
			return err
		}
	}
	for _, elem := range goo.Aunts {
		if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, elem); err != nil {
			return err
		}
	}
	return nil
}

func (goo SimpleProof) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Total != 0 {
		s += 1 + amino.VarintSize(int64(goo.Total))
	}
	if goo.Index != 0 {
		s += 1 + amino.VarintSize(int64(goo.Index))
	}
	if len(goo.LeafHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.LeafHash)
	}
	for _, elem := range goo.Aunts {
		vs := amino.ByteSliceSize(elem)
		s += 1 + vs
	}
	return s
}

func (goo *SimpleProof) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Total = int(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Index = int(v)
		case 3:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.LeafHash = nil
			} else {
				goo.LeafHash = v
			}
		case 4:
			var ev []uint8
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				ev = nil
			} else {
				ev = v
			}
			goo.Aunts = append(goo.Aunts, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 4 {
					break
				}
				bz = bz[n:]
				var ev []uint8
				v, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if len(v) == 0 {
					ev = nil
				} else {
					ev = v
				}
				goo.Aunts = append(goo.Aunts, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo SimpleProofNode) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if len(goo.Hash) != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, goo.Hash); err != nil {
			return err
		}
	}
	if goo.Parent != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Parent).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	if goo.Left != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Left).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 3, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	if goo.Right != nil {
		{
			var buf bytes.Buffer
			if err := (*goo.Right).MarshalBinary2(cdc, &buf); err != nil {
				return err
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 4, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo SimpleProofNode) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if len(goo.Hash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Hash)
	}
	if goo.Parent != nil {
		{
			cs := (*goo.Parent).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Left != nil {
		{
			cs := (*goo.Left).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Right != nil {
		{
			cs := (*goo.Right).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *SimpleProofNode) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Hash = nil
			} else {
				goo.Hash = v
			}
		case 2:
			{
				var pv SimpleProofNode
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Parent = &pv
			}
		case 3:
			{
				var pv SimpleProofNode
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Left = &pv
			}
		case 4:
			{
				var pv SimpleProofNode
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Right = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

