// Code generated by genproto2. DO NOT EDIT.

package hd

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"errors"
	"fmt"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New

func (goo BIP44Params) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.AddressIndex != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.AddressIndex))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3Varint)
	}
	if goo.Change {
		offset = amino.PrependBool(buf, offset, bool(goo.Change))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3Varint)
	}
	if goo.Account != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.Account))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.CoinType != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.CoinType))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
	}
	if goo.Purpose != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.Purpose))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo BIP44Params) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Purpose != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Purpose))
	}
	if goo.CoinType != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.CoinType))
	}
	if goo.Account != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Account))
	}
	if goo.Change {
		s += 1 + 1
	}
	if goo.AddressIndex != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.AddressIndex))
	}
	return s
}

func (goo *BIP44Params) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Purpose = uint32(v)
		case 2:
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.CoinType = uint32(v)
		case 3:
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Account = uint32(v)
		case 4:
			v, n, err := amino.DecodeBool(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Change = bool(v)
		case 5:
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.AddressIndex = uint32(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

