// Code generated by genproto2; DO NOT EDIT.

package hd

import (
	"errors"
	"fmt"
	"reflect"

	"github.com/gnolang/gno/tm2/pkg/amino"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ reflect.Type

func init() {
	amino.RegisterGenproto2Type(reflect.TypeOf((*BIP44Params)(nil)).Elem())
}

func (goo BIP44Params) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.AddressIndex != 0 {
		{
			before := offset
			offset = amino.PrependUvarint(buf, offset, uint64(goo.AddressIndex))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	if goo.Change {
		{
			before := offset
			offset = amino.PrependBool(buf, offset, bool(goo.Change))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	if goo.Account != 0 {
		{
			before := offset
			offset = amino.PrependUvarint(buf, offset, uint64(goo.Account))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	if goo.CoinType != 0 {
		{
			before := offset
			offset = amino.PrependUvarint(buf, offset, uint64(goo.CoinType))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	if goo.Purpose != 0 {
		{
			before := offset
			offset = amino.PrependUvarint(buf, offset, uint64(goo.Purpose))
			valueLen := before - offset
			if valueLen > 1 || (valueLen == 1 && buf[offset] != 0x00) {
				offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
			} else {
				offset = before
			}
		}
	}
	return offset, err
}

func (goo BIP44Params) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Purpose != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Purpose))
	}
	if goo.CoinType != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.CoinType))
	}
	if goo.Account != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Account))
	}
	if goo.Change {
		s += 1 + 1
	}
	if goo.AddressIndex != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.AddressIndex))
	}
	return s, nil
}

func (goo *BIP44Params) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	*goo = BIP44Params{}
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum <= lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Purpose = uint32(v)
		case 2:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.CoinType = uint32(v)
		case 3:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Account = uint32(v)
		case 4:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeBool(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Change = bool(v)
		case 5:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 5: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.AddressIndex = uint32(v)
		default:
			return fmt.Errorf("unknown field number %d for BIP44Params", fnum)
		}
	}
	return nil
}
