#!/usr/bin/env bash
# govdao wrapper for test12.
# Usage: ./govdao [command] [args...]
export GOVDAO_LABEL="test12"
export GNOKEY_NAME="${GNOKEY_NAME:-aeddi}"
export CHAIN_ID="${CHAIN_ID:-test12}"
export REMOTE="${REMOTE:-https://rpc.test12.aeddi.org/}"
source "$(cd "$(dirname "$0")/../../govdao-scripts" && pwd)/govdao-wrapper.sh" "$@"
