// Code generated by genproto2. DO NOT EDIT.

package bitarray

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"errors"
	"fmt"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New

func (goo BitArray) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.Elems) != 0 {
		{
			before := offset
			for i := len(goo.Elems) - 1; i >= 0; i-- {
				e := goo.Elems[i]
				offset = amino.PrependUvarint(buf, offset, uint64(e))
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if goo.Bits != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Bits))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo BitArray) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Bits != 0 {
		s += 1 + amino.VarintSize(int64(goo.Bits))
	}
	if len(goo.Elems) != 0 {
		{
			var cs int
			for _, e := range goo.Elems {
				cs += amino.UvarintSize(uint64(e))
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *BitArray) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Bits = int(v)
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			for len(fbz) > 0 {
				var ev uint64
				v, n, err := amino.DecodeUvarint(fbz)
				if err != nil {
					return err
				}
				fbz = fbz[n:]
				ev = uint64(v)
				goo.Elems = append(goo.Elems, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

