// Code generated by genproto2. DO NOT EDIT.

package bitarray

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"bytes"
	"errors"
	"fmt"
	"io"
)

var _ io.Writer
var _ fmt.Stringer
var _ *amino.Codec
var _ bytes.Buffer
var _ = errors.New

func (goo BitArray) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.Bits != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeVarint(w, int64(goo.Bits)); err != nil {
			return err
		}
	}
	if len(goo.Elems) != 0 {
		{
			var buf bytes.Buffer
			for _, e := range goo.Elems {
				if err := amino.EncodeUvarint(&buf, uint64(e)); err != nil {
					return err
				}
			}
			bz := buf.Bytes()
			if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3ByteLength); err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, bz); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo BitArray) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Bits != 0 {
		s += 1 + amino.VarintSize(int64(goo.Bits))
	}
	if len(goo.Elems) != 0 {
		{
			var cs int
			for _, e := range goo.Elems {
				cs += amino.UvarintSize(uint64(e))
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *BitArray) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Bits = int(v)
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			for len(fbz) > 0 {
				var ev uint64
				v, n, err := amino.DecodeUvarint(fbz)
				if err != nil {
					return err
				}
				fbz = fbz[n:]
				ev = uint64(v)
				goo.Elems = append(goo.Elems, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

