// Code generated by genproto2. DO NOT EDIT.

package multisig

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"bytes"
	"github.com/gnolang/gno/tm2/pkg/crypto"
	"errors"
	"fmt"
	"io"
)

var _ io.Writer
var _ fmt.Stringer
var _ *amino.Codec
var _ bytes.Buffer
var _ = errors.New

func (goo PubKeyMultisigThreshold) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if goo.K != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3Varint); err != nil {
			return err
		}
		if err := amino.EncodeUvarint(w, uint64(goo.K)); err != nil {
			return err
		}
	}
	for _, elem := range goo.PubKeys {
		if err := amino.EncodeFieldNumberAndTyp3(w, 2, amino.Typ3ByteLength); err != nil {
			return err
		}
		if elem != nil {
			anyBz, err := cdc.MarshalAny(elem)
			if err != nil {
				return err
			}
			if err := amino.EncodeByteSlice(w, anyBz); err != nil {
				return err
			}
		} else {
			if err := amino.EncodeByte(w, 0x00); err != nil {
				return err
			}
		}
	}
	return nil
}

func (goo PubKeyMultisigThreshold) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.K != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.K))
	}
	for _, elem := range goo.PubKeys {
		if elem != nil {
			anyBz, err := cdc.MarshalAny(elem)
			if err != nil {
				panic(err)
			}
			s += 1 + amino.UvarintSize(uint64(len(anyBz))) + len(anyBz)
		} else {
			s += 1 + 1
		}
	}
	return s
}

func (goo *PubKeyMultisigThreshold) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.K = uint(v)
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(fbz) > 0 {
				var ev crypto.PubKey
				if err := cdc.UnmarshalAny(fbz, &ev); err != nil {
					return err
				}
				goo.PubKeys = append(goo.PubKeys, ev)
			} else {
				goo.PubKeys = append(goo.PubKeys, nil)
			}
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 2 {
					break
				}
				bz = bz[n:]
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if len(fbz) > 0 {
					var ev crypto.PubKey
					if err := cdc.UnmarshalAny(fbz, &ev); err != nil {
						return err
					}
					goo.PubKeys = append(goo.PubKeys, ev)
				} else {
					goo.PubKeys = append(goo.PubKeys, nil)
				}
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

