networks:
  portal-loop:
    name: portal-loop
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/16

services:
  traefik:
    image: "traefik:v2.11"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik/configs"
      - "--entrypoints.rpc.address=:26657"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=dev@gno.land"
    networks:
      - portal-loop
    ports:
      - "80:80"
      - "443:443"
      - "26657:26657"
    volumes:
      - ./traefik:/etc/traefik/configs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # gnoweb:
  #   image: ghcr.io/gnolang/gno/gnoweb:master
  #   restart: unless-stopped
  #   env_file: ".env"
  #   networks:
  #     - portal-loop
  #   entrypoint:
  #     - gnoweb
  #     - --bind=0.0.0.0:8888
  #     - --remote=traefik:26657
  #     - --faucet-url
  #     - "http://localhost:5050"
  #     - --help-chainid
  #     - portal-loop
  #     - --help-remote
  #     - http://127.0.0.1:26657

  # gnofaucet:
  #   image: ghcr.io/gnolang/gno/gnofaucet-slim
  #   networks:
  #     - portal-loop
  #   ports:
  #     - 5050:5050
  #   command:
  #     - "serve"
  #     - "--listen-address=0.0.0.0:5050"
  #     - "--chain-id=portal-loop"
  #     # - "--is-behind-proxy=true"
  #     - "--mnemonic=${MNEMONIC}"
  #     # - "--num-accounts=1"
  #     - "--remote=http://traefik:26657"
  #   environment:
  #     # from .env
  #     - RECAPTCHA_SECRET_KEY

  portalloopd:
    build:
      context: ../..
      target: portalloopd
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
      - ./backups:/backups
      - ./traefik:/etc/traefik/configs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - portal-loop
    ports:
      - 9090:9090
    environment:
      HOST_PWD: $PWD
      BACKUP_DIR: "/backups"
      RPC_URL: "http://traefik:26657"
      PROM_ADDR: "0.0.0.0:9090"
      TRAEFIK_GNO_FILE: "/etc/traefik/configs/gno.yml"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  autocounterd:
    image: ghcr.io/gnolang/gno/autocounterd:latest
    restart: unless-stopped
    env_file: ".env"
    command:
      - "start"
      - "--chain-id=portal-loop"
      - "--interval=15m"
      - "--mnemonic=${COUNTER_MNEMONIC}"
      - "--rpc=http://traefik:26657"
    networks:
      - portal-loop
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    image: containrrr/watchtower
    command: --interval 30 --http-api-metrics --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/devops/.docker/config.json:/config.json
    environment:
      WATCHTOWER_HTTP_API_TOKEN: "mytoken"
    ports:
      - 127.0.0.1:8000:8080
