name: Run tests

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        go-versions: [ 1.14.x, 1.15.x, 1.16.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -race ./...
