// Code generated by genproto2. DO NOT EDIT.

package types

import (
	abci "github.com/gnolang/gno/tm2/pkg/bft/abci/types"
	"github.com/gnolang/gno/tm2/pkg/amino"
	"errors"
	"fmt"
	"time"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ time.Time

func (goo Proposal) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.Signature) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Signature)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 7, amino.Typ3ByteLength)
	}
	{
		before := offset
		offset, err = amino.PrependTime(buf, offset, goo.Timestamp)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.BlockID.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.POLRound != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.POLRound))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3Varint)
	}
	if goo.Round != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Round))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
	}
	if goo.Type != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.Type))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo Proposal) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Type != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Type))
	}
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	if goo.POLRound != 0 {
		s += 1 + amino.VarintSize(int64(goo.POLRound))
	}
	{
		cs := goo.BlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := amino.TimeSize(goo.Timestamp)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if len(goo.Signature) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Signature)
	}
	return s
}

func (goo *Proposal) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	goo.Timestamp = time.Unix(0, 0).UTC()
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = SignedMsgType(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 3:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 4:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.POLRound = int(v)
		case 5:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 6:
			// time.Time (ByteLength)
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Timestamp, _, err = amino.DecodeTime(fbz)
			if err != nil {
				return err
			}
		case 7:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Signature = nil
			} else {
				goo.Signature = v
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Block) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.LastCommit != nil {
		{
			before := offset
			offset, err = (*goo.LastCommit).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
		}
	}
	{
		before := offset
		offset, err = goo.Data.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.Header.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo Block) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.Header.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := goo.Data.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.LastCommit != nil {
		{
			cs := (*goo.LastCommit).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *Block) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Header.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Data.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 3:
			{
				var pv Commit
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.LastCommit = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Header) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.ProposerAddress != [20]byte{} {
		repr, err := goo.ProposerAddress.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 16, amino.Typ3ByteLength)
	}
	if len(goo.LastResultsHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.LastResultsHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 15, amino.Typ3ByteLength)
	}
	if len(goo.AppHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.AppHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 14, amino.Typ3ByteLength)
	}
	if len(goo.ConsensusHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.ConsensusHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 13, amino.Typ3ByteLength)
	}
	if len(goo.NextValidatorsHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.NextValidatorsHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 12, amino.Typ3ByteLength)
	}
	if len(goo.ValidatorsHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.ValidatorsHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 11, amino.Typ3ByteLength)
	}
	if len(goo.DataHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.DataHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 10, amino.Typ3ByteLength)
	}
	if len(goo.LastCommitHash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.LastCommitHash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 9, amino.Typ3ByteLength)
	}
	{
		before := offset
		offset, err = goo.LastBlockID.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 8, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.AppVersion != "" {
		offset = amino.PrependString(buf, offset, string(goo.AppVersion))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 7, amino.Typ3ByteLength)
	}
	if goo.TotalTxs != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.TotalTxs))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3Varint)
	}
	if goo.NumTxs != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.NumTxs))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3Varint)
	}
	{
		before := offset
		offset, err = amino.PrependTime(buf, offset, goo.Time)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.ChainID != "" {
		offset = amino.PrependString(buf, offset, string(goo.ChainID))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
	}
	if goo.Version != "" {
		offset = amino.PrependString(buf, offset, string(goo.Version))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo Header) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Version != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.Version))) + len(goo.Version)
	}
	if goo.ChainID != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.ChainID))) + len(goo.ChainID)
	}
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	{
		cs := amino.TimeSize(goo.Time)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.NumTxs != 0 {
		s += 1 + amino.VarintSize(int64(goo.NumTxs))
	}
	if goo.TotalTxs != 0 {
		s += 1 + amino.VarintSize(int64(goo.TotalTxs))
	}
	if goo.AppVersion != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.AppVersion))) + len(goo.AppVersion)
	}
	{
		cs := goo.LastBlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if len(goo.LastCommitHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.LastCommitHash)
	}
	if len(goo.DataHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.DataHash)
	}
	if len(goo.ValidatorsHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.ValidatorsHash)
	}
	if len(goo.NextValidatorsHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.NextValidatorsHash)
	}
	if len(goo.ConsensusHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.ConsensusHash)
	}
	if len(goo.AppHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.AppHash)
	}
	if len(goo.LastResultsHash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.LastResultsHash)
	}
	if goo.ProposerAddress != [20]byte{} {
		repr, err := goo.ProposerAddress.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 2 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	return s
}

func (goo *Header) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	goo.Time = time.Unix(0, 0).UTC()
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Version = string(v)
		case 2:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.ChainID = string(v)
		case 3:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 4:
			// time.Time (ByteLength)
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Time, _, err = amino.DecodeTime(fbz)
			if err != nil {
				return err
			}
		case 5:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.NumTxs = int64(v)
		case 6:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.TotalTxs = int64(v)
		case 7:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.AppVersion = string(v)
		case 8:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.LastBlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 9:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.LastCommitHash = nil
			} else {
				goo.LastCommitHash = v
			}
		case 10:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.DataHash = nil
			} else {
				goo.DataHash = v
			}
		case 11:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.ValidatorsHash = nil
			} else {
				goo.ValidatorsHash = v
			}
		case 12:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.NextValidatorsHash = nil
			} else {
				goo.NextValidatorsHash = v
			}
		case 13:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.ConsensusHash = nil
			} else {
				goo.ConsensusHash = v
			}
		case 14:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.AppHash = nil
			} else {
				goo.AppHash = v
			}
		case 15:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.LastResultsHash = nil
			} else {
				goo.LastResultsHash = v
			}
		case 16:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.ProposerAddress.UnmarshalAmino(repr); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Data) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.Txs) - 1; i >= 0; i-- {
		elem := goo.Txs[i]
		offset = amino.PrependByteSlice(buf, offset, elem)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo Data) SizeBinary2(cdc *amino.Codec) int {
	var s int
	for _, elem := range goo.Txs {
		vs := amino.ByteSliceSize(elem)
		s += 1 + vs
	}
	return s
}

func (goo *Data) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var ev []uint8
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				ev = nil
			} else {
				ev = v
			}
			goo.Txs = append(goo.Txs, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				bz = bz[n:]
				var ev []uint8
				v, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if len(v) == 0 {
					ev = nil
				} else {
					ev = v
				}
				goo.Txs = append(goo.Txs, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Commit) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.Precommits) - 1; i >= 0; i-- {
		elem := goo.Precommits[i]
		if elem == nil {
			offset = amino.PrependByte(buf, offset, 0x00)
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		} else {
			before := offset
			offset, err = (*elem).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	{
		before := offset
		offset, err = goo.BlockID.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo Commit) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.BlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	for _, elem := range goo.Precommits {
		if elem == nil {
			s += 1 + 1
		} else {
			cs := (*elem).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *Commit) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 2:
			var ev CommitSig
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
			goo.Precommits = append(goo.Precommits, &ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 2 {
					break
				}
				bz = bz[n:]
				var ev CommitSig
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Precommits = append(goo.Precommits, &ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo BlockID) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.PartsHeader.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if len(goo.Hash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Hash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo BlockID) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if len(goo.Hash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Hash)
	}
	{
		cs := goo.PartsHeader.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *BlockID) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Hash = nil
			} else {
				goo.Hash = v
			}
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.PartsHeader.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo CommitSig) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.Signature) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Signature)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 8, amino.Typ3ByteLength)
	}
	if goo.ValidatorIndex != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.ValidatorIndex))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 7, amino.Typ3Varint)
	}
	if goo.ValidatorAddress != [20]byte{} {
		repr, err := goo.ValidatorAddress.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3ByteLength)
	}
	{
		before := offset
		offset, err = amino.PrependTime(buf, offset, goo.Timestamp)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.BlockID.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.Round != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Round))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
	}
	if goo.Type != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.Type))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo CommitSig) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Type != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Type))
	}
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	{
		cs := goo.BlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := amino.TimeSize(goo.Timestamp)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.ValidatorAddress != [20]byte{} {
		repr, err := goo.ValidatorAddress.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.ValidatorIndex != 0 {
		s += 1 + amino.VarintSize(int64(goo.ValidatorIndex))
	}
	if len(goo.Signature) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Signature)
	}
	return s
}

func (goo *CommitSig) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	goo.Timestamp = time.Unix(0, 0).UTC()
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = SignedMsgType(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 3:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 4:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 5:
			// time.Time (ByteLength)
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Timestamp, _, err = amino.DecodeTime(fbz)
			if err != nil {
				return err
			}
		case 6:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.ValidatorAddress.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 7:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.ValidatorIndex = int(v)
		case 8:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Signature = nil
			} else {
				goo.Signature = v
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Vote) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.Signature) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Signature)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 8, amino.Typ3ByteLength)
	}
	if goo.ValidatorIndex != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.ValidatorIndex))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 7, amino.Typ3Varint)
	}
	if goo.ValidatorAddress != [20]byte{} {
		repr, err := goo.ValidatorAddress.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3ByteLength)
	}
	{
		before := offset
		offset, err = amino.PrependTime(buf, offset, goo.Timestamp)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.BlockID.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.Round != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Round))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
	}
	if goo.Type != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.Type))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo Vote) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Type != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Type))
	}
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Round != 0 {
		s += 1 + amino.VarintSize(int64(goo.Round))
	}
	{
		cs := goo.BlockID.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := amino.TimeSize(goo.Timestamp)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.ValidatorAddress != [20]byte{} {
		repr, err := goo.ValidatorAddress.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.ValidatorIndex != 0 {
		s += 1 + amino.VarintSize(int64(goo.ValidatorIndex))
	}
	if len(goo.Signature) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Signature)
	}
	return s
}

func (goo *Vote) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	goo.Timestamp = time.Unix(0, 0).UTC()
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeUvarint8(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Type = SignedMsgType(v)
		case 2:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 3:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Round = int(v)
		case 4:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.BlockID.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 5:
			// time.Time (ByteLength)
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Timestamp, _, err = amino.DecodeTime(fbz)
			if err != nil {
				return err
			}
		case 6:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.ValidatorAddress.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 7:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.ValidatorIndex = int(v)
		case 8:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Signature = nil
			} else {
				goo.Signature = v
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Part) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.Proof.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if len(goo.Bytes) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Bytes)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
	}
	if goo.Index != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Index))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo Part) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Index != 0 {
		s += 1 + amino.VarintSize(int64(goo.Index))
	}
	if len(goo.Bytes) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Bytes)
	}
	{
		cs := goo.Proof.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *Part) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Index = int(v)
		case 2:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Bytes = nil
			} else {
				goo.Bytes = v
			}
		case 3:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Proof.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo PartSet) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo PartSet) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *PartSet) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo PartSetHeader) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.Hash) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Hash)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
	}
	if goo.Total != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Total))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo PartSetHeader) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Total != 0 {
		s += 1 + amino.VarintSize(int64(goo.Total))
	}
	if len(goo.Hash) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Hash)
	}
	return s
}

func (goo *PartSetHeader) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Total = int(v)
		case 2:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Hash = nil
			} else {
				goo.Hash = v
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo Validator) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.ProposerPriority != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.ProposerPriority))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3Varint)
	}
	if goo.VotingPower != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.VotingPower))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.PubKey != nil {
		if goo.PubKey != nil {
			anyBz, err := cdc.MarshalAny(goo.PubKey)
			if err != nil {
				return offset, err
			}
			offset = amino.PrependByteSlice(buf, offset, anyBz)
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if goo.Address != [20]byte{} {
		repr, err := goo.Address.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo Validator) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Address != [20]byte{} {
		repr, err := goo.Address.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.PubKey != nil {
		if goo.PubKey != nil {
			anyBz, err := cdc.MarshalAny(goo.PubKey)
			if err != nil {
				panic(err)
			}
			s += 1 + amino.UvarintSize(uint64(len(anyBz))) + len(anyBz)
		}
	}
	if goo.VotingPower != 0 {
		s += 1 + amino.VarintSize(int64(goo.VotingPower))
	}
	if goo.ProposerPriority != 0 {
		s += 1 + amino.VarintSize(int64(goo.ProposerPriority))
	}
	return s
}

func (goo *Validator) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Address.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(fbz) > 0 {
				if err := cdc.UnmarshalAny(fbz, &goo.PubKey); err != nil {
					return err
				}
			}
		case 3:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.VotingPower = int64(v)
		case 4:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.ProposerPriority = int64(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo ValidatorSet) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Proposer != nil {
		{
			before := offset
			offset, err = (*goo.Proposer).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	for i := len(goo.Validators) - 1; i >= 0; i-- {
		elem := goo.Validators[i]
		if elem == nil {
			return offset, errors.New("nil struct pointers in lists not supported unless nil_elements field tag is also set")
		} else {
			before := offset
			offset, err = (*elem).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		}
	}
	return offset, err
}

func (goo ValidatorSet) SizeBinary2(cdc *amino.Codec) int {
	var s int
	for _, elem := range goo.Validators {
		if elem == nil {
			panic("nil struct pointers in lists not supported unless nil_elements field tag is also set")
		} else {
			cs := (*elem).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.Proposer != nil {
		{
			cs := (*goo.Proposer).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *ValidatorSet) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var ev Validator
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
			goo.Validators = append(goo.Validators, &ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				bz = bz[n:]
				var ev Validator
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Validators = append(goo.Validators, &ev)
			}
		case 2:
			{
				var pv Validator
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Proposer = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo EventNewBlock) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.ResultEndBlock.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.ResultBeginBlock.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.Block != nil {
		{
			before := offset
			offset, err = (*goo.Block).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		}
	}
	return offset, err
}

func (goo EventNewBlock) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Block != nil {
		{
			cs := (*goo.Block).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := goo.ResultBeginBlock.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := goo.ResultEndBlock.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *EventNewBlock) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			{
				var pv Block
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Block = &pv
			}
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.ResultBeginBlock.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 3:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.ResultEndBlock.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo EventNewBlockHeader) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.ResultEndBlock.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.ResultBeginBlock.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	{
		before := offset
		offset, err = goo.Header.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo EventNewBlockHeader) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.Header.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := goo.ResultBeginBlock.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	{
		cs := goo.ResultEndBlock.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *EventNewBlockHeader) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Header.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 2:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.ResultBeginBlock.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		case 3:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.ResultEndBlock.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo EventTx) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.Result.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo EventTx) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.Result.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *EventTx) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Result.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo EventVote) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Vote != nil {
		{
			before := offset
			offset, err = (*goo.Vote).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		}
	}
	return offset, err
}

func (goo EventVote) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Vote != nil {
		{
			cs := (*goo.Vote).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *EventVote) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			{
				var pv Vote
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Vote = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo EventValidatorSetUpdates) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.ValidatorUpdates) - 1; i >= 0; i-- {
		elem := goo.ValidatorUpdates[i]
		before := offset
		offset, err = elem.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo EventValidatorSetUpdates) SizeBinary2(cdc *amino.Codec) int {
	var s int
	for _, elem := range goo.ValidatorUpdates {
		cs := elem.SizeBinary2(cdc)
		s += 1 + amino.UvarintSize(uint64(cs)) + cs
	}
	return s
}

func (goo *EventValidatorSetUpdates) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var ev abci.ValidatorUpdate
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
			goo.ValidatorUpdates = append(goo.ValidatorUpdates, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				bz = bz[n:]
				var ev abci.ValidatorUpdate
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := ev.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.ValidatorUpdates = append(goo.ValidatorUpdates, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo DuplicateVoteEvidence) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.VoteB != nil {
		{
			before := offset
			offset, err = (*goo.VoteB).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
		}
	}
	if goo.VoteA != nil {
		{
			before := offset
			offset, err = (*goo.VoteA).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if goo.PubKey != nil {
		if goo.PubKey != nil {
			anyBz, err := cdc.MarshalAny(goo.PubKey)
			if err != nil {
				return offset, err
			}
			offset = amino.PrependByteSlice(buf, offset, anyBz)
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		}
	}
	return offset, err
}

func (goo DuplicateVoteEvidence) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.PubKey != nil {
		if goo.PubKey != nil {
			anyBz, err := cdc.MarshalAny(goo.PubKey)
			if err != nil {
				panic(err)
			}
			s += 1 + amino.UvarintSize(uint64(len(anyBz))) + len(anyBz)
		}
	}
	if goo.VoteA != nil {
		{
			cs := (*goo.VoteA).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.VoteB != nil {
		{
			cs := (*goo.VoteB).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *DuplicateVoteEvidence) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(fbz) > 0 {
				if err := cdc.UnmarshalAny(fbz, &goo.PubKey); err != nil {
					return err
				}
			}
		case 2:
			{
				var pv Vote
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.VoteA = &pv
			}
		case 3:
			{
				var pv Vote
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.VoteB = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo MockGoodEvidence) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Address != [20]byte{} {
		repr, err := goo.Address.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
	}
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo MockGoodEvidence) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Address != [20]byte{} {
		repr, err := goo.Address.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	return s
}

func (goo *MockGoodEvidence) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Address.UnmarshalAmino(repr); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo MockRandomGoodEvidence) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.MockGoodEvidence.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo MockRandomGoodEvidence) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.MockGoodEvidence.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *MockRandomGoodEvidence) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.MockGoodEvidence.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo MockBadEvidence) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.MockGoodEvidence.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo MockBadEvidence) SizeBinary2(cdc *amino.Codec) int {
	var s int
	{
		cs := goo.MockGoodEvidence.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *MockBadEvidence) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.MockGoodEvidence.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo TxResult) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.Response.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if len(goo.Tx) != 0 {
		offset = amino.PrependByteSlice(buf, offset, goo.Tx)
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
	}
	if goo.Index != 0 {
		offset = amino.PrependUvarint(buf, offset, uint64(goo.Index))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
	}
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo TxResult) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	if goo.Index != 0 {
		s += 1 + amino.UvarintSize(uint64(goo.Index))
	}
	if len(goo.Tx) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Tx)
	}
	{
		cs := goo.Response.SizeBinary2(cdc)
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *TxResult) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		case 2:
			v, n, err := amino.DecodeUvarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Index = uint32(v)
		case 3:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Tx = nil
			} else {
				goo.Tx = v
			}
		case 4:
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Response.UnmarshalBinary2(cdc, fbz); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo MockAppState) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.AccountOwner != "" {
		offset = amino.PrependString(buf, offset, string(goo.AccountOwner))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MockAppState) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.AccountOwner != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.AccountOwner))) + len(goo.AccountOwner)
	}
	return s
}

func (goo *MockAppState) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.AccountOwner = string(v)
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo VoteSet) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo VoteSet) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *VoteSet) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

