package mock

func main() {
	// f := New_F()

	// f.Add("apple")
	// f.Add("banana")

	// // f.fsm.Format_StateMachine("some_func")

	// f.Fuzz(func(t *T, orig ...interface{}) {
	// 	v, ok := orig[0].(string)
	// 	if !ok {
	// 		panic("dont match")
	// 	}
	// 	rev := fuzzinglib.Reverse1(v)
	// 	doubleRev := fuzzinglib.Reverse1(rev)
	// 	if v != doubleRev {
	// 		t.Errorf("Before: %q, after: %q", orig, doubleRev)
	// 	}
	// 	if utf8.ValidString(v) && !utf8.ValidString(rev) {
	// 		t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
	// 	}
	// })
	println("hellasdasddso wsdsadorld!sss")
}
