// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: multisig.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// messages
type PubKeyMultisig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K       uint64       `protobuf:"varint,1,opt,name=K,proto3" json:"K,omitempty"`
	PubKeys []*anypb.Any `protobuf:"bytes,2,rep,name=PubKeys,proto3" json:"PubKeys,omitempty"`
}

func (x *PubKeyMultisig) Reset() {
	*x = PubKeyMultisig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multisig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKeyMultisig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyMultisig) ProtoMessage() {}

func (x *PubKeyMultisig) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyMultisig.ProtoReflect.Descriptor instead.
func (*PubKeyMultisig) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{0}
}

func (x *PubKeyMultisig) GetK() uint64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *PubKeyMultisig) GetPubKeys() []*anypb.Any {
	if x != nil {
		return x.PubKeys
	}
	return nil
}

var File_multisig_proto protoreflect.FileDescriptor

var file_multisig_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x74, 0x6d, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4e, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69,
	0x67, 0x12, 0x0c, 0x0a, 0x01, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x4b, 0x12,
	0x2e, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6e,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6e, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x73, 0x2f, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multisig_proto_rawDescOnce sync.Once
	file_multisig_proto_rawDescData = file_multisig_proto_rawDesc
)

func file_multisig_proto_rawDescGZIP() []byte {
	file_multisig_proto_rawDescOnce.Do(func() {
		file_multisig_proto_rawDescData = protoimpl.X.CompressGZIP(file_multisig_proto_rawDescData)
	})
	return file_multisig_proto_rawDescData
}

var file_multisig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multisig_proto_goTypes = []interface{}{
	(*PubKeyMultisig)(nil), // 0: tm.PubKeyMultisig
	(*anypb.Any)(nil),      // 1: google.protobuf.Any
}
var file_multisig_proto_depIdxs = []int32{
	1, // 0: tm.PubKeyMultisig.PubKeys:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_multisig_proto_init() }
func file_multisig_proto_init() {
	if File_multisig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multisig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubKeyMultisig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multisig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multisig_proto_goTypes,
		DependencyIndexes: file_multisig_proto_depIdxs,
		MessageInfos:      file_multisig_proto_msgTypes,
	}.Build()
	File_multisig_proto = out.File
	file_multisig_proto_rawDesc = nil
	file_multisig_proto_goTypes = nil
	file_multisig_proto_depIdxs = nil
}
