package stdlibs

import (
	gno "github.com/gnolang/gno/gnovm/pkg/gnolang"
)

// Per-native gas charging. Calibrated values come from
// gnovm/cmd/calibrate/native_bench_test.go (and its machine-harness
// companion); the python fitter at gnovm/cmd/calibrate/gen_native_table.py
// emits the literal table below.
//
// Registration is at init time into a package global in gnolang
// (RegisterNativeGas). Mirrors how OpCPU* constants live in gnolang —
// no per-Machine resolver plumbing.
//
// Calibration is end-to-end through doOpCallNativeBody (Gno↔Go reflect +
// X_ work + return push); no separate dispatch overhead constant.

// Re-export the gnolang SizeKind constants for readable table literals.
const (
	SizeFlat          = gno.SizeFlat
	SizeLenBytes      = gno.SizeLenBytes
	SizeLenString     = gno.SizeLenString
	SizeLenSlice      = gno.SizeLenSlice
	SizeNumCallFrames = gno.SizeNumCallFrames
	SizeReturnLen     = gno.SizeReturnLen
)

// nativeGasEntry is the on-disk shape of a row, copied into a
// gno.NativeGasInfo at init time.
type nativeGasEntry struct {
	Pkg, Fn   string
	Base      int64
	Slope     int64
	SlopeIdx  int8
	SlopeKind gno.NativeGasSize

	// Post-call charge (zero = none). PostSlopeIdx is the stack offset
	// from top (1 = last-pushed return); PostSlopeKind must be a
	// SizeReturn* kind.
	PostBase      int64
	PostSlope     int64
	PostSlopeIdx  int8
	PostSlopeKind gno.NativeGasSize
}

// Calibrated on Apple M2 ARM64 (NOT the reference Xeon 8168 — re-run
// gnovm/cmd/calibrate before any consensus-relevant deployment). 1 gas
// = 1 ns. Slope is ns per 1024 units of N. R² > 0.99 for all linear fits.
//
// Generated by gen_native_table.py from native_bench_output.txt; if
// you regenerate, paste only the entries — keep the worst-case-baked
// SizeFlat overrides for SizeReturnLen natives noted below.
var calibratedNativeGas = []nativeGasEntry{
	{Pkg: "crypto/sha256", Fn: "sum256", Base: 231, Slope: 9395, SlopeIdx: 0, SlopeKind: SizeLenBytes},
	{Pkg: "crypto/ed25519", Fn: "verify", Base: 53545, Slope: 9137, SlopeIdx: 1, SlopeKind: SizeLenBytes},
	{Pkg: "chain", Fn: "packageAddress", Base: 543, Slope: 16763, SlopeIdx: 0, SlopeKind: SizeLenString},
	{Pkg: "chain", Fn: "deriveStorageDepositAddr", Base: 532, Slope: 456, SlopeIdx: 0, SlopeKind: SizeLenString},
	{Pkg: "chain", Fn: "pubKeyAddress", Base: 2594, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "time", Fn: "loadFromEmbeddedTZData", Base: 18635, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "math", Fn: "Float32bits", Base: 33, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "math", Fn: "Float32frombits", Base: 38, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "math", Fn: "Float64bits", Base: 29, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "math", Fn: "Float64frombits", Base: 31, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/banker", Fn: "bankerSendCoins", Base: 319, Slope: 34719, SlopeIdx: 3, SlopeKind: SizeLenSlice},
	// bankerGetCoins → (denoms []string, amounts []int64). Slope on the
	// returned coin count. PostSlopeIdx=2 reads `denoms` (amounts is on
	// top of stack as the last-pushed return).
	{Pkg: "chain/banker", Fn: "bankerGetCoins",
		Base: 339, SlopeIdx: -1, SlopeKind: SizeFlat,
		PostSlope: 38040, PostSlopeIdx: 2, PostSlopeKind: SizeReturnLen},
	{Pkg: "chain/banker", Fn: "bankerTotalCoin", Base: 88, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/banker", Fn: "bankerIssueCoin", Base: 137, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/banker", Fn: "bankerRemoveCoin", Base: 137, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/banker", Fn: "originSend", Base: 197, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/banker", Fn: "assertCallerIsRealm", Base: 467, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain", Fn: "emit", Base: 297, Slope: 31597, SlopeIdx: 1, SlopeKind: SizeLenSlice},
	{Pkg: "chain/params", Fn: "SetBytes", Base: 1344, Slope: 9134, SlopeIdx: 1, SlopeKind: SizeLenBytes},
	{Pkg: "chain/params", Fn: "SetString", Base: 1136, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/params", Fn: "SetStrings", Base: 1222, Slope: 23462, SlopeIdx: 1, SlopeKind: SizeLenSlice},
	{Pkg: "chain/params", Fn: "SetBool", Base: 1108, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/params", Fn: "SetInt64", Base: 1117, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/params", Fn: "SetUint64", Base: 1111, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "sys/params", Fn: "setSysParamBytes", Base: 291, Slope: 9239, SlopeIdx: 4, SlopeKind: SizeLenBytes},
	// getSysParamBytes → (value []byte, found bool). Slope on returned
	// byte count. PostSlopeIdx=2 reads `value` (bool is on top of stack).
	{Pkg: "sys/params", Fn: "getSysParamBytes",
		Base: 407, SlopeIdx: -1, SlopeKind: SizeFlat,
		PostSlope: 11113, PostSlopeIdx: 2, PostSlopeKind: SizeReturnLen},
	{Pkg: "chain/runtime", Fn: "ChainID", Base: 44, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/runtime", Fn: "ChainDomain", Base: 44, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/runtime", Fn: "ChainHeight", Base: 30, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/runtime", Fn: "originCaller", Base: 44, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/runtime", Fn: "getSessionInfo", Base: 147, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/runtime", Fn: "AssertOriginCall", Base: 5, SlopeIdx: -1, SlopeKind: SizeFlat},
	{Pkg: "chain/runtime", Fn: "getRealm", Base: 990, Slope: 1320, SlopeIdx: -1, SlopeKind: SizeNumCallFrames},
	{Pkg: "time", Fn: "now", Base: 48, SlopeIdx: -1, SlopeKind: SizeFlat},
}

func init() {
	for _, e := range calibratedNativeGas {
		gno.RegisterNativeGas(e.Pkg, gno.Name(e.Fn), &gno.NativeGasInfo{
			Base:          e.Base,
			Slope:         e.Slope,
			SlopeIdx:      e.SlopeIdx,
			SlopeKind:     e.SlopeKind,
			PostBase:      e.PostBase,
			PostSlope:     e.PostSlope,
			PostSlopeIdx:  e.PostSlopeIdx,
			PostSlopeKind: e.PostSlopeKind,
		})
	}
}
