version: "2"

services:
  gnoland:
    container_name: gnoland
    build: ../../..
    environment:
      - LOG_LEVEL=4
      - VIRTUAL_HOST=rpc.test3.gno.land
      - VIRTUAL_PORT=36657
      - LETSENCRYPT_HOST=rpc.test3.gno.land
    command:
      - gnoland
      - start
      - --skip-failing-genesis-txs
      - --chainid
      - test3
      - --genesis-remote
      - test3.gno.land:36657
      - --genesis-balances-file
      - /overlay/balances.txt
      - --genesis-txs-file
      - /overlay/genesis_txs.txt
    volumes:
      - "./data/gnoland:/opt/gno/src/testdir"
      - "./overlay:/overlay:ro"
    ports:
      - 36656:36656
      - 36657:36657
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  gnoweb:
    container_name: gnoweb
    build: ../../..
    command:
      - gnoweb
      - --bind
      - 0.0.0.0:80
      - --remote
      - gnoland:36657
      - --captcha-site
      - $RECAPTCHA_SITE_KEY
      - --faucet-url
      - https://faucet.test3.gno.land/
      - --help-chainid
      - test3
      - --help-remote
      - test3.gno.land:36657
      - --home-content
      - /overlay/HOME.md
    volumes:
      - "./overlay:/overlay:ro"
    links:
      - gnoland
    environment:
      - VIRTUAL_HOST=test3.gno.land
      - LETSENCRYPT_HOST=test3.gno.land
      # from .env
      - RECAPTCHA_SITE_KEY
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  gnofaucet:
    container_name: gnofaucet
    build: ../../..
    command: sh -xc "
        date &&
        mkdir -p /.gno &&
        expect -c \"set timeout -1; spawn gnokey add faucet --home /.gno/ --recover; expect \\\"Enter a passphrase\\\"; send \\\"$GNOKEY_PASS\\r\\\"; expect \\\"Repeat the passphrase\\\"; send \\\"$GNOKEY_PASS\\r\\\"; expect \\\"Enter your bip39 mnemonic\\\"; send \\\"$FAUCET_WORDS\\r\\\"; expect eof\" &&
        while true; do
          expect -c \"set timeout -1; spawn gnofaucet serve faucet --is-behind-proxy --send 50000000ugnot --captcha-secret \\\"$RECAPTCHA_SECRET_KEY\\\" --remote gnoland:36657 --chain-id test3 --home /.gno/; expect \\\"Enter password.\\\"; send \\\"$GNOKEY_PASS\\r\\\"; expect eof\";
          sleep 5;
        done
      "
    links:
      - gnoland
    environment:
      - VIRTUAL_HOST=faucet.test3.gno.land
      - VIRTUAL_PORT=5050
      - LETSENCRYPT_HOST=faucet.test3.gno.land
      # from .env
      - RECAPTCHA_SECRET_KEY
      - FAUCET_WORDS
      - GNOKEY_PASS
    ports:
      - 5050
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=noreply@gno.land
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
