// You can edit this code!
// Click here and start typing.
package main

var v int = 1

func main() {
	v++
	if v >= 1 {
		v++
		println(v)
		if v >= 1 {
			v++
			println(v)
			if v >= 1 {
				v++
				println(v)
				if v >= 1 {
					v++
					println(v)
					if v >= 1 {
						v++
						println(v)

						if v >= 1 {
							v++
							println(v)
							if v >= 1 {
								v++
								println(v)
								if v >= 1 {
									v++
									println(v)
									if v >= 1 {
										v++
										println(v)

										if v >= 1 {
											v++
											println(v)
											if v >= 1 {
												v++
												println(v)

												if v >= 1 {
													v++
													println(v)
													if v >= 1 {
														v++
														println(v)

														if v >= 1 {
															v++
															println(v)
															if v >= 1 {
																v++
																println(v)

																if v >= 1 {
																	v++
																	println(v)
																	if v >= 1 {
																		v++
																		println(v)
																		if v >= 1 {
																			v++
																			println(v)
																			if v >= 1 {
																				v++
																				println(v)
																				if v >= 1 {
																					v++
																					println(v)
																					if v >= 1 {
																						v++
																						println(v)

																						if v >= 1 {
																							v++
																							println(v)
																							if v >= 1 {
																								v++
																								println(v)
																								if v >= 1 {
																									v++
																									println(v)
																									if v >= 1 {
																										v++
																										println(v)

																										if v >= 1 {
																											v++
																											println(v)
																											if v >= 1 {
																												v++
																												println(v)

																												if v >= 1 {
																													v++
																													println(v)
																													if v >= 1 {
																														v++
																														println(v)

																														if v >= 1 {
																															v++
																															println(v)
																															if v >= 1 {
																																v++
																																println(v)

																																if v >= 1 {
																																	v++
																																	println(v)
																																	if v >= 1 {
																																		v++
																																		println(v)
																																		if v >= 1 {
																																			v++
																																			println(v)
																																			if v >= 1 {
																																				v++
																																				println(v)
																																				if v >= 1 {
																																					v++
																																					println(v)
																																					if v >= 1 {
																																						v++
																																						println(v)

																																						if v >= 1 {
																																							v++
																																							println(v)
																																							if v >= 1 {
																																								v++
																																								println(v)
																																								if v >= 1 {
																																									v++
																																									println(v)
																																									if v >= 1 {
																																										v++
																																										println(v)

																																										if v >= 1 {
																																											v++
																																											println(v)
																																											if v >= 1 {
																																												v++
																																												println(v)

																																												if v >= 1 {
																																													v++
																																													println(v)
																																													if v >= 1 {
																																														v++
																																														println(v)

																																														if v >= 1 {
																																															v++
																																															println(v)
																																															if v >= 1 {
																																																v++
																																																println(v)

																																																if v >= 1 {
																																																	v++
																																																	println(v)
																																																	if v >= 1 {
																																																		v++
																																																		println(v)
																																																		if v >= 1 {
																																																			v++
																																																			println(v)
																																																			if v >= 1 {
																																																				v++
																																																				println(v)
																																																				if v >= 1 {
																																																					v++
																																																					println(v)
																																																					if v >= 1 {
																																																						v++
																																																						println(v)

																																																						if v >= 1 {
																																																							v++
																																																							println(v)
																																																							if v >= 1 {
																																																								v++
																																																								println(v)
																																																								if v >= 1 {
																																																									v++
																																																									println(v)
																																																									if v >= 1 {
																																																										v++
																																																										println(v)

																																																										if v >= 1 {
																																																											v++
																																																											println(v)
																																																											if v >= 1 {
																																																												v++
																																																												println(v)

																																																												if v >= 1 {
																																																													v++
																																																													println(v)
																																																													if v >= 1 {
																																																														v++
																																																														println(v)

																																																														if v >= 1 {
																																																															v++
																																																															println(v)
																																																															if v >= 1 {
																																																																v++
																																																																println(v)

																																																																if v >= 1 {
																																																																	v++
																																																																	println(v)
																																																																	if v >= 1 {
																																																																		v++
																																																																		println(v)
																																																																		if v >= 1 {
																																																																			v++
																																																																			println(v)
																																																																			if v >= 1 {
																																																																				v++
																																																																				println(v)
																																																																				if v >= 1 {
																																																																					v++
																																																																					println(v)
																																																																					if v >= 1 {
																																																																						v++
																																																																						println(v)

																																																																						if v >= 1 {
																																																																							v++
																																																																							println(v)
																																																																							if v >= 1 {
																																																																								v++
																																																																								println(v)
																																																																								if v >= 1 {
																																																																									v++
																																																																									println(v)
																																																																									if v >= 1 {
																																																																										v++
																																																																										println(v)

																																																																										if v >= 1 {
																																																																											v++
																																																																											println(v)
																																																																											if v >= 1 {
																																																																												v++
																																																																												println(v)

																																																																												if v >= 1 {
																																																																													v++
																																																																													println(v)
																																																																													if v >= 1 {
																																																																														v++
																																																																														println(v)

																																																																														if v >= 1 {
																																																																															v++
																																																																															println(v)
																																																																															if v >= 1 {
																																																																																v++
																																																																																println(v)

																																																																																if v >= 1 {
																																																																																	v++
																																																																																	println(v)
																																																																																	if v >= 1 {
																																																																																		v++
																																																																																		println(v)
																																																																																		if v >= 1 {
																																																																																			v++
																																																																																			println(v)
																																																																																			if v >= 1 {
																																																																																				v++
																																																																																				println(v)
																																																																																				if v >= 1 {
																																																																																					v++
																																																																																					println(v)
																																																																																					if v >= 1 {
																																																																																						v++
																																																																																						println(v)

																																																																																						if v >= 1 {
																																																																																							v++
																																																																																							println(v)
																																																																																							if v >= 1 {
																																																																																								v++
																																																																																								println(v)
																																																																																								if v >= 1 {
																																																																																									v++
																																																																																									println(v)
																																																																																									if v >= 1 {
																																																																																										v++
																																																																																										println(v)

																																																																																										if v >= 1 {
																																																																																											v++
																																																																																											println(v)
																																																																																											if v >= 1 {
																																																																																												v++
																																																																																												println(v)

																																																																																												if v >= 1 {
																																																																																													v++
																																																																																													println(v)
																																																																																													if v >= 1 {
																																																																																														v++
																																																																																														println(v)

																																																																																														if v >= 1 {
																																																																																															v++
																																																																																															println(v)
																																																																																															if v >= 1 {
																																																																																																v++
																																																																																																println(v)

																																																																																																if v >= 1 {
																																																																																																	v++
																																																																																																	println(v)
																																																																																																	if v >= 1 {
																																																																																																		v++
																																																																																																		println(v)
																																																																																																		if v >= 1 {
																																																																																																			v++
																																																																																																			println(v)
																																																																																																			if v >= 1 {
																																																																																																				v++
																																																																																																				println(v)
																																																																																																				if v >= 1 {
																																																																																																					v++
																																																																																																					println(v)
																																																																																																					if v >= 1 {
																																																																																																						v++
																																																																																																						println(v)

																																																																																																						if v >= 1 {
																																																																																																							v++
																																																																																																							println(v)
																																																																																																							if v >= 1 {
																																																																																																								v++
																																																																																																								println(v)
																																																																																																								if v >= 1 {
																																																																																																									v++
																																																																																																									println(v)
																																																																																																									if v >= 1 {
																																																																																																										v++
																																																																																																										println(v)

																																																																																																										if v >= 1 {
																																																																																																											v++
																																																																																																											println(v)
																																																																																																											if v >= 1 {
																																																																																																												v++
																																																																																																												println(v)

																																																																																																												if v >= 1 {
																																																																																																													v++
																																																																																																													println(v)
																																																																																																													if v >= 1 {
																																																																																																														v++
																																																																																																														println(v)

																																																																																																														if v >= 1 {
																																																																																																															v++
																																																																																																															println(v)
																																																																																																															if v >= 1 {
																																																																																																																v++
																																																																																																																println(v)

																																																																																																																if v >= 1 {
																																																																																																																	v++
																																																																																																																	println(v)
																																																																																																																	if v >= 1 {
																																																																																																																		v++
																																																																																																																		println(v)
																																																																																																																		if v >= 1 {
																																																																																																																			v++
																																																																																																																			println(v)
																																																																																																																			if v >= 1 {
																																																																																																																				v++
																																																																																																																				println(v)
																																																																																																																				if v >= 1 {
																																																																																																																					v++
																																																																																																																					println(v)
																																																																																																																					if v >= 1 {
																																																																																																																						v++
																																																																																																																						println(v)

																																																																																																																						if v >= 1 {
																																																																																																																							v++
																																																																																																																							println(v)
																																																																																																																							if v >= 1 {
																																																																																																																								v++
																																																																																																																								println(v)
																																																																																																																								if v >= 1 {
																																																																																																																									v++
																																																																																																																									println(v)
																																																																																																																									if v >= 1 {
																																																																																																																										v++
																																																																																																																										println(v)

																																																																																																																										if v >= 1 {
																																																																																																																											v++
																																																																																																																											println(v)
																																																																																																																											if v >= 1 {
																																																																																																																												v++
																																																																																																																												println(v)

																																																																																																																												if v >= 1 {
																																																																																																																													v++
																																																																																																																													println(v)
																																																																																																																													if v >= 1 {
																																																																																																																														v++
																																																																																																																														println(v)
																																																																																																																													}
																																																																																																																												}
																																																																																																																											}
																																																																																																																										}
																																																																																																																									}
																																																																																																																								}
																																																																																																																							}
																																																																																																																						}
																																																																																																																					}
																																																																																																																				}
																																																																																																																			}
																																																																																																																		}
																																																																																																																	}
																																																																																																																}
																																																																																																															}
																																																																																																														}
																																																																																																													}
																																																																																																												}
																																																																																																											}
																																																																																																										}
																																																																																																									}
																																																																																																								}
																																																																																																							}
																																																																																																						}
																																																																																																					}
																																																																																																				}
																																																																																																			}
																																																																																																		}
																																																																																																	}
																																																																																																}
																																																																																															}
																																																																																														}
																																																																																													}
																																																																																												}
																																																																																											}
																																																																																										}
																																																																																									}
																																																																																								}
																																																																																							}
																																																																																						}
																																																																																					}
																																																																																				}
																																																																																			}
																																																																																		}
																																																																																	}
																																																																																}
																																																																															}
																																																																														}
																																																																													}
																																																																												}
																																																																											}
																																																																										}
																																																																									}
																																																																								}
																																																																							}
																																																																						}
																																																																					}
																																																																				}
																																																																			}
																																																																		}
																																																																	}
																																																																}
																																																															}
																																																														}
																																																													}
																																																												}
																																																											}
																																																										}
																																																									}
																																																								}
																																																							}
																																																						}
																																																					}
																																																				}
																																																			}
																																																		}
																																																	}
																																																}
																																															}
																																														}
																																													}
																																												}
																																											}
																																										}
																																									}
																																								}
																																							}
																																						}
																																					}
																																				}
																																			}
																																		}
																																	}
																																}
																															}
																														}
																													}
																												}
																											}
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}

// Error:
// main/block2.gno:419:129-130: exceeded maximum VPBlock depth (127)
