package std

import (
	"fmt"
	"strconv"

	"github.com/gnolang/gno/tm2/pkg/amino"
	"github.com/gnolang/gno/tm2/pkg/crypto"
)

// SignDoc is the standard object for transactions.
// AccountNumber is a replay-prevention field for the whole account
// (eg. nonce) to prevent the replay of txs after an account has been deleted
// (due to zero balance). Sequence is a replay-prevention field for each transaction
// given a nonce
type SignDoc struct {
	ChainID       string `json:"chain_id" yaml:"chain_id"`
	AccountNumber uint64 `json:"account_number" yaml:"account_number"`
	Sequence      uint64 `json:"sequence" yaml:"sequence"`
	Fee           Fee    `json:"fee" yaml:"fee"`
	Msgs          []Msg  `json:"msgs" yaml:"msgs"`
	Memo          string `json:"memo" yaml:"memo"`
}

// signDocFee is the fee as it appears in the signature payload.
//
// It is deliberately NOT std.Fee. The Ledger Cosmos app -- which gno has no
// app of its own and therefore borrows -- validates the amino sign doc against
// a fixed allowlist of keys, and refuses to sign anything containing a key it
// does not know. Inside "fee" it permits only amount, gas, granter and payer
// (ledger-cosmos, app/src/tx_validate.c).
//
// std.Fee renders as {"gas_wanted":...,"gas_fee":"1000000ugnot"}, so every gno
// transaction -- a send as much as an addpkg -- is refused with "Unexpected
// field" before the device will display anything. Three things differ from what
// the app expects: the key names, the cardinality (one Coin against an array),
// and the numeric type (amino JSON renders these as strings).
type signDocFee struct {
	Amount []signDocCoin `json:"amount"`
	Gas    string        `json:"gas"`
}

// signDocCoin spells out a Coin, because amino renders std.Coin as the single
// string "1000000ugnot" and the allowlist wants an object.
type signDocCoin struct {
	Denom  string `json:"denom"`
	Amount string `json:"amount"`
}

// signDocPayload mirrors SignDoc with the fee in the form above. Every other
// field already matches what the app allows, so only the fee is restated.
type signDocPayload struct {
	ChainID       string     `json:"chain_id"`
	AccountNumber uint64     `json:"account_number"`
	Sequence      uint64     `json:"sequence"`
	Fee           signDocFee `json:"fee"`
	Msgs          []Msg      `json:"msgs"`
	Memo          string     `json:"memo"`
}

// GetSignaturePayload returns the sign payload for the SignDoc.
// The signature payload is generated by marshalling the SignDoc
// into Amino JSON, and then sorting the Amino JSON.
// Ultimately, the formula for signing is sign(sortJSON(aminoJSON(SignDoc)))
func GetSignaturePayload(s SignDoc) ([]byte, error) {
	// Prepare the amino JSON
	data, err := amino.MarshalJSON(signDocPayload{
		ChainID:       s.ChainID,
		AccountNumber: s.AccountNumber,
		Sequence:      s.Sequence,
		Fee: signDocFee{
			Amount: []signDocCoin{{
				Denom:  s.Fee.GasFee.Denom,
				Amount: strconv.FormatInt(s.Fee.GasFee.Amount, 10),
			}},
			Gas: strconv.FormatInt(s.Fee.GasWanted, 10),
		},
		Msgs: s.Msgs,
		Memo: s.Memo,
	})
	if err != nil {
		return nil, fmt.Errorf("unable to marshal sign doc, %w", err)
	}

	// Sort the JSON
	sortedData, err := sortJSON(data)
	if err != nil {
		return nil, fmt.Errorf("unable to sort payload JSON, %w", err)
	}

	return sortedData, nil
}

// Signature represents a wrapped signature of a transaction
type Signature struct {
	PubKey    crypto.PubKey `json:"pub_key" yaml:"pub_key"` // optional
	Signature []byte        `json:"signature" yaml:"signature"`
	// SessionAddr identifies a session account for delegated signing.
	// Zero-value means a master-key signature. When non-zero, the AnteHandler
	// loads the session account at /a/<signer>/s/<SessionAddr> for verification.
	// Amino binary and JSON both skip the field when the address is zero
	// ([20]byte{}), so master-signed txs pay no wire-size overhead.
	SessionAddr crypto.Address `json:"session_addr,omitempty" yaml:"session_addr,omitempty"`
}
