// Code generated by genproto2. DO NOT EDIT.

package vm

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"errors"
	"fmt"
	"github.com/gnolang/gno/tm2/pkg/std"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New

func (goo MsgCall) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.Args) - 1; i >= 0; i-- {
		elem := goo.Args[i]
		offset = amino.PrependString(buf, offset, string(elem))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3ByteLength)
	}
	if goo.Func != "" {
		offset = amino.PrependString(buf, offset, string(goo.Func))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3ByteLength)
	}
	if goo.PkgPath != "" {
		offset = amino.PrependString(buf, offset, string(goo.PkgPath))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
	}
	if len(goo.MaxDeposit) != 0 {
		repr, err := goo.MaxDeposit.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
	}
	if len(goo.Send) != 0 {
		repr, err := goo.Send.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
	}
	if goo.Caller != [20]byte{} {
		repr, err := goo.Caller.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MsgCall) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Caller != [20]byte{} {
		repr, err := goo.Caller.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if len(goo.Send) != 0 {
		repr, err := goo.Send.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if len(goo.MaxDeposit) != 0 {
		repr, err := goo.MaxDeposit.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.PkgPath != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.PkgPath))) + len(goo.PkgPath)
	}
	if goo.Func != "" {
		s += 1 + amino.UvarintSize(uint64(len(goo.Func))) + len(goo.Func)
	}
	for _, elem := range goo.Args {
		vs := amino.UvarintSize(uint64(len(elem))) + len(elem)
		s += 1 + vs
	}
	return s
}

func (goo *MsgCall) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Caller.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Send.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 3:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.MaxDeposit.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 4:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.PkgPath = string(v)
		case 5:
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Func = string(v)
		case 6:
			var ev string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			ev = string(v)
			goo.Args = append(goo.Args, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 6 {
					break
				}
				bz = bz[n:]
				var ev string
				v, n, err := amino.DecodeString(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				ev = string(v)
				goo.Args = append(goo.Args, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo MsgRun) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Package != nil {
		{
			before := offset
			offset, err = (*goo.Package).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
		}
	}
	if len(goo.MaxDeposit) != 0 {
		repr, err := goo.MaxDeposit.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
	}
	if len(goo.Send) != 0 {
		repr, err := goo.Send.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
	}
	if goo.Caller != [20]byte{} {
		repr, err := goo.Caller.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MsgRun) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Caller != [20]byte{} {
		repr, err := goo.Caller.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if len(goo.Send) != 0 {
		repr, err := goo.Send.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if len(goo.MaxDeposit) != 0 {
		repr, err := goo.MaxDeposit.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.Package != nil {
		{
			cs := (*goo.Package).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s
}

func (goo *MsgRun) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Caller.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Send.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 3:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.MaxDeposit.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 4:
			{
				var pv std.MemPackage
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Package = &pv
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo MsgAddPackage) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if len(goo.MaxDeposit) != 0 {
		repr, err := goo.MaxDeposit.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
	}
	if len(goo.Send) != 0 {
		repr, err := goo.Send.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3ByteLength)
	}
	if goo.Package != nil {
		{
			before := offset
			offset, err = (*goo.Package).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MsgAddPackage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.Package != nil {
		{
			cs := (*goo.Package).SizeBinary2(cdc)
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if len(goo.Send) != 0 {
		repr, err := goo.Send.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if len(goo.MaxDeposit) != 0 {
		repr, err := goo.MaxDeposit.MarshalAmino()
		if err != nil {
			return 0
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	return s
}

func (goo *MsgAddPackage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Creator.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			{
				var pv std.MemPackage
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz); err != nil {
					return err
				}
				goo.Package = &pv
			}
		case 3:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Send.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 4:
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.MaxDeposit.UnmarshalAmino(repr); err != nil {
				return err
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo InvalidPkgPathError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo InvalidPkgPathError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *InvalidPkgPathError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo NoRenderDeclError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo NoRenderDeclError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *NoRenderDeclError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo PkgExistError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo PkgExistError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *PkgExistError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo InvalidStmtError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo InvalidStmtError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *InvalidStmtError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo InvalidExprError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo InvalidExprError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *InvalidExprError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo TypeCheckError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	for i := len(goo.Errors) - 1; i >= 0; i-- {
		elem := goo.Errors[i]
		offset = amino.PrependString(buf, offset, string(elem))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo TypeCheckError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	for _, elem := range goo.Errors {
		vs := amino.UvarintSize(uint64(len(elem))) + len(elem)
		s += 1 + vs
	}
	return s
}

func (goo *TypeCheckError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			var ev string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			ev = string(v)
			goo.Errors = append(goo.Errors, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				nextFnum, _, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 1 {
					break
				}
				bz = bz[n:]
				var ev string
				v, n, err := amino.DecodeString(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				ev = string(v)
				goo.Errors = append(goo.Errors, ev)
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo UnauthorizedUserError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo UnauthorizedUserError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *UnauthorizedUserError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo InvalidPackageError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo InvalidPackageError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *InvalidPackageError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

func (goo InvalidFileError) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	return offset, err
}

func (goo InvalidFileError) SizeBinary2(cdc *amino.Codec) int {
	var s int
	return s
}

func (goo *InvalidFileError) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

