version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github_actions"

  # Maintain dependencies for top level Go modules
  - package-ecosystem: gomod
    directory: /
    target-branch: "main"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "zivkovicmilos"