#!/usr/bin/env bash
# Generate betanet genesis.json.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
EXAMPLES_DIR="$REPO_ROOT/examples"

# Resolve listed realms + all transitive deps in topological order.
pkg_dirs=$(cd "$EXAMPLES_DIR" && gno tool deplist \
    ./gno.land/r/sys/... \
    ./gno.land/r/gov/... \
    ./gno.land/r/gnoland/blog/... \
    ./gno.land/r/gnoland/wugnot/... \
    ./gno.land/r/gnoland/coins/... \
    ./gno.land/r/gnoland/boards2/... \
)

# Save resolved package list for inspection.
{ echo "# Generated by gen-genesis.sh — do not edit."; echo "$pkg_dirs" | sed "s|$EXAMPLES_DIR/||g"; } > "$SCRIPT_DIR/packages.gen.txt"

# Copy resolved packages into a staging directory.
STAGING=$(mktemp -d)
trap 'rm -rf "$STAGING"' EXIT
while IFS= read -r dir; do
    [[ -z "$dir" ]] && continue
    rel="${dir#$EXAMPLES_DIR/}"
    mkdir -p "$(dirname "$STAGING/$rel")"
    cp -r "$dir" "$STAGING/$rel"
done <<< "$pkg_dirs"

# Strip test files — they pull in deps (like uassert) not needed in genesis.
find "$STAGING" -name '*_test.gno' -delete
find "$STAGING" -name '*_filetest.gno' -delete

# Build genesis.
# The default deployer is the well-known test1 key (see gnogenesis source).
# It needs enough balance to cover gas fees + storage deposits for all txs.
GENESIS="$SCRIPT_DIR/genesis.json"
gnogenesis generate -chain-id betanet -output-path "$GENESIS"
gnogenesis validator add \
    -name placeholder \
    -power 1 \
    -address g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5 \
    -pub-key gpub1pgfj7ard9eg82cjtv4u4xetrwqer2dntxyfzxz3pq0skzdkmzu0r9h6gny6eg8c9dc303xrrudee6z4he4y7cs5rnjwmyf40yaj \
    -genesis-path "$GENESIS"
gnogenesis balances add \
    -single g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5=100000000000ugnot \
    -genesis-path "$GENESIS"
gnogenesis txs add packages "$STAGING" -genesis-path "$GENESIS"

echo "Done: $GENESIS"
