// Code generated by genproto2; DO NOT EDIT.

package secp256k1

import (
	"errors"
	"fmt"
	"reflect"

	"github.com/gnolang/gno/tm2/pkg/amino"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ reflect.Type

func init() {
	amino.RegisterGenproto2Type(reflect.TypeOf((*PubKeySecp256k1)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*PrivKeySecp256k1)(nil)).Elem())
}

func (goo PubKeySecp256k1) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	repr := goo
	if len(repr) > 0 {
		before := offset
		for i := len(repr) - 1; i >= 0; i-- {
			elem := repr[i]
			offset = amino.PrependByte(buf, offset, uint8(elem))
		}
		dataLen := before - offset
		offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo PubKeySecp256k1) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	repr := goo
	if len(repr) > 0 {
		var cs int
		cs = len(repr)
		s += 1 + amino.UvarintSize(uint64(cs)) + cs
	}
	return s, nil
}

func (goo *PubKeySecp256k1) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	return cdc.UnmarshalReflect(bz, goo)
}

func (goo PrivKeySecp256k1) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	repr := goo
	if len(repr) > 0 {
		before := offset
		for i := len(repr) - 1; i >= 0; i-- {
			elem := repr[i]
			offset = amino.PrependByte(buf, offset, uint8(elem))
		}
		dataLen := before - offset
		offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo PrivKeySecp256k1) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	repr := goo
	if len(repr) > 0 {
		var cs int
		cs = len(repr)
		s += 1 + amino.UvarintSize(uint64(cs)) + cs
	}
	return s, nil
}

func (goo *PrivKeySecp256k1) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	return cdc.UnmarshalReflect(bz, goo)
}
