// Code generated by genproto2; DO NOT EDIT.

package auth

import (
	"errors"
	"fmt"
	"reflect"

	"github.com/gnolang/gno/tm2/pkg/amino"
	"github.com/gnolang/gno/tm2/pkg/crypto"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ reflect.Type

func init() {
	amino.RegisterGenproto2Type(reflect.TypeOf((*GenesisState)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*Params)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*MsgCreateSession)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*MsgRevokeSession)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*MsgRevokeAllSessions)(nil)).Elem())
}

func (goo GenesisState) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	{
		before := offset
		offset, err = goo.Params.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	return offset, err
}

func (goo GenesisState) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	{
		cs, err := goo.Params.SizeBinary2(cdc)
		if err != nil {
			return 0, err
		}
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s, nil
}

func (goo *GenesisState) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.Params.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unknown field number %d for GenesisState", fnum)
		}
	}
	return nil
}

func (goo Params) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.FeeCollector != [20]byte{} {
		repr, err := goo.FeeCollector.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 10, amino.Typ3ByteLength)
	}
	for i := len(goo.UnrestrictedAddrs) - 1; i >= 0; i-- {
		elem := goo.UnrestrictedAddrs[i]
		er, err := elem.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(er))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 9, amino.Typ3ByteLength)
	}
	{
		before := offset
		offset, err = goo.InitialGasPrice.MarshalBinary2(cdc, buf, offset)
		if err != nil {
			return offset, err
		}
		dataLen := before - offset
		if dataLen > 0 {
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 8, amino.Typ3ByteLength)
		} else {
			offset = before
		}
	}
	if goo.TargetGasRatio != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.TargetGasRatio))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 7, amino.Typ3Varint)
	}
	if goo.GasPricesChangeCompressor != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.GasPricesChangeCompressor))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3Varint)
	}
	if goo.SigVerifyCostSecp256k1 != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.SigVerifyCostSecp256k1))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3Varint)
	}
	if goo.SigVerifyCostED25519 != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.SigVerifyCostED25519))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3Varint)
	}
	if goo.TxSizeCostPerByte != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.TxSizeCostPerByte))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.TxSigLimit != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.TxSigLimit))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3Varint)
	}
	if goo.MaxMemoBytes != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.MaxMemoBytes))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo Params) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.MaxMemoBytes != 0 {
		s += 1 + amino.VarintSize(int64(goo.MaxMemoBytes))
	}
	if goo.TxSigLimit != 0 {
		s += 1 + amino.VarintSize(int64(goo.TxSigLimit))
	}
	if goo.TxSizeCostPerByte != 0 {
		s += 1 + amino.VarintSize(int64(goo.TxSizeCostPerByte))
	}
	if goo.SigVerifyCostED25519 != 0 {
		s += 1 + amino.VarintSize(int64(goo.SigVerifyCostED25519))
	}
	if goo.SigVerifyCostSecp256k1 != 0 {
		s += 1 + amino.VarintSize(int64(goo.SigVerifyCostSecp256k1))
	}
	if goo.GasPricesChangeCompressor != 0 {
		s += 1 + amino.VarintSize(int64(goo.GasPricesChangeCompressor))
	}
	if goo.TargetGasRatio != 0 {
		s += 1 + amino.VarintSize(int64(goo.TargetGasRatio))
	}
	{
		cs, err := goo.InitialGasPrice.SizeBinary2(cdc)
		if err != nil {
			return 0, err
		}
		if cs > 0 {
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	for _, elem := range goo.UnrestrictedAddrs {
		er, err := elem.MarshalAmino()
		if err != nil {
			return 0, err
		}
		vs := amino.UvarintSize(uint64(len(er))) + len(er)
		s += 1 + vs
	}
	if goo.FeeCollector != [20]byte{} {
		repr, err := goo.FeeCollector.MarshalAmino()
		if err != nil {
			return 0, err
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	return s, nil
}

func (goo *Params) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.MaxMemoBytes = int64(v)
		case 2:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.TxSigLimit = int64(v)
		case 3:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.TxSizeCostPerByte = int64(v)
		case 4:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.SigVerifyCostED25519 = int64(v)
		case 5:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 5: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.SigVerifyCostSecp256k1 = int64(v)
		case 6:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 6: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.GasPricesChangeCompressor = int64(v)
		case 7:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 7: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.TargetGasRatio = int64(v)
		case 8:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 8: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if err := goo.InitialGasPrice.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
				return err
			}
		case 9:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 9: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var ev crypto.Address
			var rv string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			rv = string(v)
			if err := ev.UnmarshalAmino(rv); err != nil {
				return err
			}
			goo.UnrestrictedAddrs = append(goo.UnrestrictedAddrs, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				var nextTyp3 amino.Typ3
				nextFnum, nextTyp3, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 9 {
					break
				}
				if nextTyp3 != amino.Typ3ByteLength {
					return fmt.Errorf("field 9: expected typ3 %v, got %v", amino.Typ3ByteLength, nextTyp3)
				}
				bz = bz[n:]
				var ev crypto.Address
				var rv string
				v, n, err := amino.DecodeString(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				rv = string(v)
				if err := ev.UnmarshalAmino(rv); err != nil {
					return err
				}
				goo.UnrestrictedAddrs = append(goo.UnrestrictedAddrs, ev)
			}
		case 10:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 10: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.FeeCollector.UnmarshalAmino(repr); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unknown field number %d for Params", fnum)
		}
	}
	return nil
}

func (goo MsgCreateSession) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.SpendPeriod != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.SpendPeriod))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 6, amino.Typ3Varint)
	}
	if len(goo.SpendLimit) != 0 {
		repr, err := goo.SpendLimit.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 5, amino.Typ3ByteLength)
	}
	for i := len(goo.AllowPaths) - 1; i >= 0; i-- {
		elem := goo.AllowPaths[i]
		offset = amino.PrependString(buf, offset, string(elem))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 4, amino.Typ3ByteLength)
	}
	if goo.ExpiresAt != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.ExpiresAt))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 3, amino.Typ3Varint)
	}
	if goo.SessionKey != nil {
		if goo.SessionKey != nil {
			before := offset
			offset, err = cdc.MarshalAnyBinary2(goo.SessionKey, buf, offset)
			if err != nil {
				return offset, err
			}
			anyLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(anyLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MsgCreateSession) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return 0, err
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.SessionKey != nil {
		if goo.SessionKey != nil {
			cs, err := cdc.SizeAnyBinary2(goo.SessionKey)
			if err != nil {
				return 0, err
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	if goo.ExpiresAt != 0 {
		s += 1 + amino.VarintSize(int64(goo.ExpiresAt))
	}
	for _, elem := range goo.AllowPaths {
		vs := amino.UvarintSize(uint64(len(elem))) + len(elem)
		s += 1 + vs
	}
	if len(goo.SpendLimit) != 0 {
		repr, err := goo.SpendLimit.MarshalAmino()
		if err != nil {
			return 0, err
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.SpendPeriod != 0 {
		s += 1 + amino.VarintSize(int64(goo.SpendPeriod))
	}
	return s, nil
}

func (goo *MsgCreateSession) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Creator.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(fbz) > 0 {
				if err := cdc.UnmarshalAnyBinary2(fbz, &goo.SessionKey, anyDepth); err != nil {
					return err
				}
			}
		case 3:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 3: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.ExpiresAt = int64(v)
		case 4:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var ev string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			ev = string(v)
			goo.AllowPaths = append(goo.AllowPaths, ev)
			for len(bz) > 0 {
				var nextFnum uint32
				var nextTyp3 amino.Typ3
				nextFnum, nextTyp3, n, err = amino.DecodeFieldNumberAndTyp3(bz)
				if err != nil {
					return err
				}
				if nextFnum != 4 {
					break
				}
				if nextTyp3 != amino.Typ3ByteLength {
					return fmt.Errorf("field 4: expected typ3 %v, got %v", amino.Typ3ByteLength, nextTyp3)
				}
				bz = bz[n:]
				var ev string
				v, n, err := amino.DecodeString(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				ev = string(v)
				goo.AllowPaths = append(goo.AllowPaths, ev)
			}
		case 5:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 5: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.SpendLimit.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 6:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 6: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.SpendPeriod = int64(v)
		default:
			return fmt.Errorf("unknown field number %d for MsgCreateSession", fnum)
		}
	}
	return nil
}

func (goo MsgRevokeSession) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.SessionKey != nil {
		if goo.SessionKey != nil {
			before := offset
			offset, err = cdc.MarshalAnyBinary2(goo.SessionKey, buf, offset)
			if err != nil {
				return offset, err
			}
			anyLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(anyLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 2, amino.Typ3ByteLength)
		}
	}
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MsgRevokeSession) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return 0, err
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	if goo.SessionKey != nil {
		if goo.SessionKey != nil {
			cs, err := cdc.SizeAnyBinary2(goo.SessionKey)
			if err != nil {
				return 0, err
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s, nil
}

func (goo *MsgRevokeSession) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Creator.UnmarshalAmino(repr); err != nil {
				return err
			}
		case 2:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 2: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			fbz, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(fbz) > 0 {
				if err := cdc.UnmarshalAnyBinary2(fbz, &goo.SessionKey, anyDepth); err != nil {
					return err
				}
			}
		default:
			return fmt.Errorf("unknown field number %d for MsgRevokeSession", fnum)
		}
	}
	return nil
}

func (goo MsgRevokeAllSessions) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return offset, err
		}
		offset = amino.PrependString(buf, offset, string(repr))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
	}
	return offset, err
}

func (goo MsgRevokeAllSessions) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Creator != [20]byte{} {
		repr, err := goo.Creator.MarshalAmino()
		if err != nil {
			return 0, err
		}
		s += 1 + amino.UvarintSize(uint64(len(repr))) + len(repr)
	}
	return s, nil
}

func (goo *MsgRevokeAllSessions) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			var repr string
			v, n, err := amino.DecodeString(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			repr = string(v)
			if err := goo.Creator.UnmarshalAmino(repr); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unknown field number %d for MsgRevokeAllSessions", fnum)
		}
	}
	return nil
}
