// Code generated by genproto2; DO NOT EDIT.

package blockchain

import (
	"errors"
	"fmt"
	"reflect"
	"time"

	"github.com/gnolang/gno/tm2/pkg/amino"
	"github.com/gnolang/gno/tm2/pkg/bft/types"
)

var _ fmt.Stringer
var _ *amino.Codec
var _ = errors.New
var _ reflect.Type
var _ time.Time

func init() {
	amino.RegisterGenproto2Type(reflect.TypeOf((*bcBlockRequestMessage)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*bcBlockResponseMessage)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*bcNoBlockResponseMessage)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*bcStatusRequestMessage)(nil)).Elem())
	amino.RegisterGenproto2Type(reflect.TypeOf((*bcStatusResponseMessage)(nil)).Elem())
}

func (goo bcBlockRequestMessage) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo bcBlockRequestMessage) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	return s, nil
}

func (goo *bcBlockRequestMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		default:
			return fmt.Errorf("unknown field number %d for bcBlockRequestMessage", fnum)
		}
	}
	return nil
}

func (goo bcBlockResponseMessage) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Block != nil {
		{
			before := offset
			offset, err = (*goo.Block).MarshalBinary2(cdc, buf, offset)
			if err != nil {
				return offset, err
			}
			dataLen := before - offset
			offset = amino.PrependUvarint(buf, offset, uint64(dataLen))
			offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3ByteLength)
		}
	}
	return offset, err
}

func (goo bcBlockResponseMessage) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Block != nil {
		{
			cs, err := (*goo.Block).SizeBinary2(cdc)
			if err != nil {
				return 0, err
			}
			s += 1 + amino.UvarintSize(uint64(cs)) + cs
		}
	}
	return s, nil
}

func (goo *bcBlockResponseMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3ByteLength {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3ByteLength, typ3)
			}
			{
				var pv types.Block
				fbz, n, err := amino.DecodeByteSlice(bz)
				if err != nil {
					return err
				}
				bz = bz[n:]
				if err := pv.UnmarshalBinary2(cdc, fbz, anyDepth); err != nil {
					return err
				}
				goo.Block = &pv
			}
		default:
			return fmt.Errorf("unknown field number %d for bcBlockResponseMessage", fnum)
		}
	}
	return nil
}

func (goo bcNoBlockResponseMessage) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo bcNoBlockResponseMessage) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	return s, nil
}

func (goo *bcNoBlockResponseMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		default:
			return fmt.Errorf("unknown field number %d for bcNoBlockResponseMessage", fnum)
		}
	}
	return nil
}

func (goo bcStatusRequestMessage) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo bcStatusRequestMessage) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	return s, nil
}

func (goo *bcStatusRequestMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		default:
			return fmt.Errorf("unknown field number %d for bcStatusRequestMessage", fnum)
		}
	}
	return nil
}

func (goo bcStatusResponseMessage) MarshalBinary2(cdc *amino.Codec, buf []byte, offset int) (int, error) {
	var err error
	if goo.Height != 0 {
		offset = amino.PrependVarint(buf, offset, int64(goo.Height))
		offset = amino.PrependFieldNumberAndTyp3(buf, offset, 1, amino.Typ3Varint)
	}
	return offset, err
}

func (goo bcStatusResponseMessage) SizeBinary2(cdc *amino.Codec) (int, error) {
	var s int
	if goo.Height != 0 {
		s += 1 + amino.VarintSize(int64(goo.Height))
	}
	return s, nil
}

func (goo *bcStatusResponseMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte, anyDepth int) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		_ = typ3
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			if typ3 != amino.Typ3Varint {
				return fmt.Errorf("field 1: expected typ3 %v, got %v", amino.Typ3Varint, typ3)
			}
			v, n, err := amino.DecodeVarint(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			goo.Height = int64(v)
		default:
			return fmt.Errorf("unknown field number %d for bcStatusResponseMessage", fnum)
		}
	}
	return nil
}
