
## gno.land params

["bank"]
  restricted_denoms = ["gnot"]

["vm"]
  chain_domain = "gno.land"
  sysnames_pkgpath = "gno.land/r/sys/names"
  # TODO: Leverage toml unmarshaler to extract these into VM Params struct before writing to genesis
  # TODO: max_gas = 100_000_000
  # TODO: chain_tz = "UTC"
  # TODO: default_storage_allowance = ""

["auth"]
  # TODO: max_memo_bytes = 65536
  # TODO: tx_sig_limit = 7
  # TODO: tx_size_cost_per_byte = 10
  # TODO: sig_verify_cost_ed25519 = 590
  # TODO: sig_verify_cost_secp256k1 = 1000
  # TODO: GasPricesChangeCompressor = 10
  # TODO: TargetGasRatio = 70
  fee_collector = "g1najfm5t7dr4f2m38cg55xt6gh2lxsk92tgh0xy" # "gno.land/r/sys/txfees"

["tm2"]
  # TODO

#######################################
## realm parameters example
#
# ["vm:gno.land/r/sys/testrealm"]
#   foo_string = "bar"
#   foo_int64 = -1337
#   foo_uint64 = 123
#   foo_bool = true
#   "foo_strings.strings" = ["some", "strings"]
#   # foo_bytes = ...?
