// Code generated by "stringer -type=Word ./pkg/gnolang"; DO NOT EDIT.

package gnolang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[NAME-1]
	_ = x[INT-2]
	_ = x[FLOAT-3]
	_ = x[IMAG-4]
	_ = x[CHAR-5]
	_ = x[STRING-6]
	_ = x[ADD-7]
	_ = x[SUB-8]
	_ = x[MUL-9]
	_ = x[QUO-10]
	_ = x[REM-11]
	_ = x[BAND-12]
	_ = x[BOR-13]
	_ = x[XOR-14]
	_ = x[SHL-15]
	_ = x[SHR-16]
	_ = x[BAND_NOT-17]
	_ = x[ADD_ASSIGN-18]
	_ = x[SUB_ASSIGN-19]
	_ = x[MUL_ASSIGN-20]
	_ = x[QUO_ASSIGN-21]
	_ = x[REM_ASSIGN-22]
	_ = x[BAND_ASSIGN-23]
	_ = x[BOR_ASSIGN-24]
	_ = x[XOR_ASSIGN-25]
	_ = x[SHL_ASSIGN-26]
	_ = x[SHR_ASSIGN-27]
	_ = x[BAND_NOT_ASSIGN-28]
	_ = x[LAND-29]
	_ = x[LOR-30]
	_ = x[ARROW-31]
	_ = x[INC-32]
	_ = x[DEC-33]
	_ = x[EQL-34]
	_ = x[LSS-35]
	_ = x[GTR-36]
	_ = x[ASSIGN-37]
	_ = x[NOT-38]
	_ = x[NEQ-39]
	_ = x[LEQ-40]
	_ = x[GEQ-41]
	_ = x[DEFINE-42]
	_ = x[BREAK-43]
	_ = x[CASE-44]
	_ = x[CHAN-45]
	_ = x[CONST-46]
	_ = x[CONTINUE-47]
	_ = x[DEFAULT-48]
	_ = x[DEFER-49]
	_ = x[ELSE-50]
	_ = x[FALLTHROUGH-51]
	_ = x[FOR-52]
	_ = x[FUNC-53]
	_ = x[GO-54]
	_ = x[GOTO-55]
	_ = x[IF-56]
	_ = x[IMPORT-57]
	_ = x[INTERFACE-58]
	_ = x[MAP-59]
	_ = x[PACKAGE-60]
	_ = x[RANGE-61]
	_ = x[RETURN-62]
	_ = x[SELECT-63]
	_ = x[STRUCT-64]
	_ = x[SWITCH-65]
	_ = x[TYPE-66]
	_ = x[VAR-67]
}

const _Word_name = "ILLEGALNAMEINTFLOATIMAGCHARSTRINGADDSUBMULQUOREMBANDBORXORSHLSHRBAND_NOTADD_ASSIGNSUB_ASSIGNMUL_ASSIGNQUO_ASSIGNREM_ASSIGNBAND_ASSIGNBOR_ASSIGNXOR_ASSIGNSHL_ASSIGNSHR_ASSIGNBAND_NOT_ASSIGNLANDLORARROWINCDECEQLLSSGTRASSIGNNOTNEQLEQGEQDEFINEBREAKCASECHANCONSTCONTINUEDEFAULTDEFERELSEFALLTHROUGHFORFUNCGOGOTOIFIMPORTINTERFACEMAPPACKAGERANGERETURNSELECTSTRUCTSWITCHTYPEVAR"

var _Word_index = [...]uint16{0, 7, 11, 14, 19, 23, 27, 33, 36, 39, 42, 45, 48, 52, 55, 58, 61, 64, 72, 82, 92, 102, 112, 122, 133, 143, 153, 163, 173, 188, 192, 195, 200, 203, 206, 209, 212, 215, 221, 224, 227, 230, 233, 239, 244, 248, 252, 257, 265, 272, 277, 281, 292, 295, 299, 301, 305, 307, 313, 322, 325, 332, 337, 343, 349, 355, 361, 365, 368}

func (i Word) String() string {
	if i < 0 || i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
