name: benchmarks
on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
      test-flags:
        required: true
        type: string

env:
  CGO_ENABLED: 0

jobs:
  benchmarks:
    if: ${{ github.repository == 'gnolang/gno' }}
    runs-on: [self-hosted, Linux, X64, benchmark-v1]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"
    - name: "gobenchdata publish: ${{ inputs.publish }}"
      run: go run go.bobheadxi.dev/gobenchdata@v1 action
      env:
        INPUT_PRUNE_COUNT: 30
        INPUT_GO_TEST_FLAGS: "${{ inputs.test-flags }} -run=^$ -cpu 1,2" # executing only using one and two CPUs to not be dependant on the machine cores.
        INPUT_PUBLISH: ${{ inputs.publish }}
        INPUT_PUBLISH_BRANCH: gh-benchmarks
        INPUT_BENCHMARKS_OUT: benchmarks.json
        INPUT_CHECKS: ${{ !inputs.publish }}
        INPUT_CHECKS_CONFIG: .benchmarks/gobenchdata-checks.yml
