name: run benchmarks on every PR

### TODO: change
# on:
#   pull_request:
on:
  push:
    branches: [ "dummy-benchmark" ]

jobs:
  check:
    uses: ./.github/workflows/benchmark_template.yml
    secrets: inherit
    with:
      publish: false
      test-flags: "-short"
      external-data-json-path: "./cache/benchmark-data.json"