name: run benchmarks on every PR

on:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/benchmark_template.yml
    secrets: inherit
    with:
      publish: false
      test-flags: "-short"