name: run benchmarks on main branch every day

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # run on default branch every day
jobs:
  publish:
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      publish: true
      test-flags: "-timeout 50m"