name: run benchmarks on every PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      publish: false
      test-flags: "-short"