name: benchmarks
on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
      test-flags:
        required: true
        type: string

env:
  CGO_ENABLED: 0

jobs:
  benchmarks:
    if: ${{ github.repository == 'gnolang/gno' }}
    runs-on: [self-hosted, Linux, X64, benchmark-v1]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"
    - name: Run benchmark
      run: go test -benchmem -bench=. -run=^$ ./... -cpu 1,2 ${{ inputs.test-flags }} | tee benchmarks.txt

    - name: Store benchmark result - separate results repo
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Go Benchmark
        tool: 'go'
        output-file-path: benchmarks.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        # fail-on-alert: true
        # alert-comment-cc-users: '@ajnavarro'
        gh-repository: 'github.com/gnolang/benchmarks'
