name: run benchmarks on main branch every day

### TODO: change
# on:
#   workflow_dispatch:
#   schedule:
#     - cron:  '0 0 * * *' # run on default branch every day
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # run on default branch every day

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/benchmark_template.yml
    secrets: inherit
    with:
      publish: true
      # test-flags: "-timeout 50m"
      test-flags: "-short"