name: ci / codegen-verify

on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "misc/genproto/**"
      - "misc/genproto2/**"
      - "docs/**"
      - ".github/workflows/ci-codegen-verify.yml"
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "misc/genproto/**"
      - "misc/genproto2/**"
      - "docs/**"
      - ".github/workflows/ci-codegen-verify.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - run: make tidy VERIFY_MOD_SUMS=true

  genproto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - run: sudo apt update && sudo apt install -y libprotobuf-dev protobuf-compiler
      - run: make -C misc/devdeps install
      - run: |
          make -C misc/genproto
          git diff --text --exit-code || (echo "Some .proto files are not updated, please run 'make -C misc/genproto'." && exit 1)

  genproto2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - run: |
          make -C misc/genproto2
          git diff --text --exit-code || (echo "Some pb3_gen.go files are not updated, please run 'make -C misc/genproto2'." && exit 1)

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - working-directory: docs/
        run: make generate -B
      - run: |
          diff=$(git status --porcelain)
          if [[ $diff ]]; then
              echo "Please run 'make generate' in docs/."
              exit 1
          fi
      - working-directory: docs/
        run: make lint
