name: ci / gnoland

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - gno.land/**
      - gnovm/**
      - tm2/**
      - examples/**
      - go.mod
      - .github/workflows/ci-dir-gnoland.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    uses: ./.github/workflows/_ci-go.yml
    with:
      modulepath: "gno.land"
      tests-extra-args: "-coverpkg=github.com/gnolang/gno/gno.land/..."
      # FIXME(gfanton): run txtar integration test sequentially to avoid timeout
      tests-ts-seq: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  gnoweb_generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/Jod
      - run: |
          make -C gno.land/pkg/gnoweb fclean generate
          git diff --exit-code || \
             (echo "'gnoweb generate' out of date, please run 'make gnoweb.generate' within './gno.land'" && exit 1)

  gnoweb_front_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/Jod
      - run: make -C gno.land/pkg/gnoweb/frontend lint.ci
