name: ci / gnoland

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - gno.land/**
      - gnovm/**
      - tm2/**
      - examples/**
      - go.mod
      - .github/workflows/ci-dir-gnoland.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    uses: ./.github/workflows/_ci-go.yml
    with:
      modulepath: "gno.land"
      tests-extra-args: "-coverpkg=github.com/gnolang/gno/gno.land/..."
      # FIXME(gfanton): run txtar integration test sequentially to avoid timeout
      tests-ts-seq: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  gnoweb_generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/Jod
      - run: |
          make -C gno.land/pkg/gnoweb fclean generate
          git diff --exit-code || \
             (echo "'gnoweb generate' out of date, please run 'make gnoweb.generate' within './gno.land'" && exit 1)

  gnoweb_front_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/Jod
      - run: make -C gno.land/pkg/gnoweb/frontend lint.ci
