name: code generation

on:
  push:
    branches: [ "master" ]
  pull_request:
    paths:
      - 'gnovm/stdlibs/**'
      - 'gnovm/tests/stdlibs/**'
      - 'misc/genstd'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generated:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check generated files are up to date
        run: |
          go generate -x ./...
          if [ "$(git status -s)" != "" ]; then
            echo "command 'go generate' creates file that differ from git tree, please run 'go generate' and commit:"
            git status -s
            exit 1
          fi

