# This workflow triggers a cross-repo workflow call,
# that deploys the monorepo docs on Netlify, using Docusaurus
name: deploy / docs
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

permissions: {}

jobs:
  trigger-netlify-docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          github-token: ${{ secrets.DOCS_DEPLOY_PAT }} # zizmor: ignore[secrets-outside-env]
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: 'gnolang',
                repo: 'docs.gno.land',
                workflow_id: 'netlify.yml',
                ref: 'main'
            })
