name: Docker Bake Build And Push

on:
  push:
    branches:
      - refactor/gnoland-home
      - feat/docker-bake
      - chain/test*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  bake:
    # Match only branches whose name is chain/test[0-9][0-9]
    # if: startsWith(github.ref, 'refs/heads/chain/test') && github.ref =~ '^refs/heads/chain/test[0-9][0-9]$'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
       
      - name: Set Multiple ENV Variables
        run: |
          REF_NAME="${{ github.ref_name }}"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            REF_NAME="${REF_NAME#v}"
          fi
          REF_NAME="${REF_NAME//\//_}"
          echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "VERSION=${REF_NAME}-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV
      
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/gnoland
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
          labels: |
            org.opencontainers.image.authors=Gno Core Team

      # Using Github Context. Overriding context with an explicit `set` is required
      - name: Bake build and push
        uses: docker/bake-action@v6
        with:
          files: |
            misc/deployments/bake/docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-tags }}
            cwd://${{ steps.meta.outputs.bake-file-labels }}
          ### TBmodified
          push: true
          target: gnoland
          platforms: linux/amd64
          ###
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.context=.
        env:
          DATE: ${{ env.NOW }}
          FULL_COMMIT: ${{ github.sha }}
          VERSION: ${{ env.VERSION }}
          TAG: ${{ env.REF_NAME }}
