name: Docker Bake Build And Push

on:
  push:
    branches:
      - refactor/gnoland-home
      - feat/docker-bak
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
       
      - name: Set Multiple ENV Variables
        run: |
          REF_NAME="${{ github.ref_name }}"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            REF_NAME="${REF_NAME#v}"
          fi
          REF_NAME="${REF_NAME//\//_}"
          echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "VERSION=${REF_NAME}-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV

      # Using Github Context. Overriding context with an explicit `set` is required
      - name: Bake build and push
        uses: docker/bake-action@v6
        with:
          files: misc/deployments/bake/docker-bake.hcl
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.context=.
        env:
          DATE: ${{ env.NOW }}
          FULL_COMMIT: ${{ github.sha }}
          VERSION: ${{ env.VERSION }}
          TAG: ${{ env.REF_NAME }}
