# The purpose of this is removing a folder from AWS S3 when a PR is merged
name: Docs Deploy - Remove PR Folder in AWS S3 Bucket

on:
  pull_request:
    types:
      - closed
    paths:
      - "docs/**"
      - "docusaurus/**"

jobs:
  remove-s3:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Remove from S3
      uses: vitorsgomes/s3-rm-action@master
      with:
        args: --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: docs.gno.land
        PATH_TO_DELETE: ${{ github.event.pull_request.base.sha }}

    - name: Comment the issue
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 The PR was merged and the relative doc preview has been removed. Please refer to production doc to see the changes relative to this PR'
          })
