name: Docs Linter

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (docs builder)
        uses: actions/setup-go@v5
        with:
          go-version-file: misc/devdeps/go.mod

      - name: Install dependencies (docs builder)
        working-directory: misc/devdeps
        run: go mod download

      - name: Set up Go (docs linter)
        uses: actions/setup-go@v5
        with:
          go-version-file: misc/docs/tools/linter/go.mod

      - name: Install dependencies (docs linter)
        working-directory: misc/docs/tools/linter
        run: go mod download

      - name: Run linter
        run: make -C docs/ lint
