name: gno

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  main:
    name: Run Main
    uses: ./.github/workflows/main_template.yml
    with:
      modulepath: "gno"
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  fmt:
    name: Run Gno Fmt
    uses: ./.github/workflows/gnofmt_template.yml
    with:
      path: "gno/stdlibs/..."
      go-version: "1.22.x"
