name: gnofaucet

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request: 
    paths:
      - "contribs/gnofaucet/**"
      - ".github/**"

jobs:
  main:
    name: Run Main
    uses: ./.github/workflows/main_template.yml
    with:
      modulepath: "contribs/gnofaucet"
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}