name: gnomod

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request: 
    paths:
      - "contribs/gnomod/**"
      - ".github/**"

jobs:
  main:
    name: Run Main
    uses: ./.github/workflows/main_template.yml
    with:
      modulepath: "contribs/gnomod"