on:
    workflow_call:
        inputs:
            modulepath:
              required: true
              type: string
        secrets:
          codecov-token:
            required: true
env:
  GOVERSION: 1.22.x

jobs:
    lint:
        name: Go Linter
        uses: ./.github/workflows/lint_template.yml
        with:
            modulepath: ${{ inputs.modulepath }}
    build:
        name: Go Build
        uses: ./.github/workflows/build_template.yml
        with:
            modulepath: ${{ inputs.modulepath }}
    test:
        name: Go Test
        uses: ./.github/workflows/test_template.yml
        with:
            modulepath: ${{ inputs.modulepath }}
            tests-timeout: "30m"
        secrets:
            codecov-token: ${{ secrets.codecov-token }}
    