on:
    workflow_call:
        inputs:
            modulepath:
              required: true
              type: string
        secrets:
          codecov-token:
            required: true

# TODO: environment variables cannot be sent to reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
# env:
#   GO_VERSION: "1.22.x"

jobs:
    lint:
        name: Go Linter
        uses: ./.github/workflows/lint_template.yml
        with:
            modulepath: ${{ inputs.modulepath }}
            go-version: "1.22.x"
    build:
        name: Go Build
        uses: ./.github/workflows/build_template.yml
        with:
            modulepath: ${{ inputs.modulepath }}
            go-version: "1.22.x"
    test:
        name: Go Test
        uses: ./.github/workflows/test_template.yml
        with:
            modulepath: ${{ inputs.modulepath }}
            tests-timeout: "30m"
            go-version: "1.22.x"
        secrets:
            codecov-token: ${{ secrets.codecov-token }}
    