name: meta / fossa

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    if: github.repository == 'gnolang/gno'
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          persist-credentials: false

      - name: Move .fossa.yml to root dir
        run: mv .github/.fossa.yml .

      - name: Cache Coursier cache
        uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # 6.4.7

      - name: Set up JDK 17
        uses: coursier/setup-action@039f736548afa5411c1382f40a5bd9c2d30e0383 # v1.3.9
        with:
          jvm: temurin:1.17

      - name: Set up fossa CLI
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash"

      - name: FOSSA analyze
        run: fossa analyze
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}" # zizmor: ignore[secrets-outside-env]
