name: meta / fossa

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    if: github.repository == 'gnolang/gno'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          persist-credentials: false

      - name: Move .fossa.yml to root dir
        run: mv .github/.fossa.yml .

      - name: Cache Coursier cache
        uses: coursier/cache-action@90c37294538be80a558fd665531fcdc2b467b475 # 8.1.0

      - name: Set up JDK 17
        uses: coursier/setup-action@fd1707a76b027efdfb66ca79318b4d29b72e5a02 # v3.0.0
        with:
          jvm: temurin:1.17

      - name: Set up fossa CLI
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash"

      - name: FOSSA analyze
        run: fossa analyze
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}" # zizmor: ignore[secrets-outside-env]
