name: meta / gh / labeler
on:
  - pull_request_target # zizmor: ignore[dangerous-triggers]

permissions: {}

jobs:
  check:
    permissions:
      contents: write # to read .github/labeler.yml config
      issues: write # to add labels to issues
      pull-requests: write # to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
