name: meta / actions-lint

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**
  workflow_dispatch:

permissions: {}

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - name: Download actionlint
        run: |
          curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash | bash # v1.7.12
        shell: bash
      - name: Run actionlint
        run: ./actionlint -color
        shell: bash

  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # to upload SARIF results to the Security tab
      contents: read
      actions: read # to read workflow files for analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
