name: meta / dependabot-tidy

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "**/go.mod"
      - "**/go.sum"

permissions: {}

jobs:
  tidy_go_mods:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: write # to commit the tidied go.mod/go.sum files
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Tidy all Go mods
        env:
          VERIFY_MOD_SUMS: false
        run: |
          # Ensure Make is installed
          make --version

          # Run the tidy target
          make tidy

      - name: Commit changes, if any
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip_dirty_check: false # Enable dirty check, and skip unnecessary committing
          commit_message: "Run 'go mod tidy' via GitHub Actions"
