name: meta / gh / assign

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [ opened, reopened ]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to auto-assign the PR author
    steps:
      - uses: toshimaru/auto-author-assign@4d585cc37690897bd9015942ed6e766aa7cdb97f # v3.0.1
