name: Monthly Snapshots

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate tag name
        id: tag_name
        run: echo "::set-output name=tag_name::v0.0.1-dev.$(date +'%Y.%m.%d')"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          tag_name: '${{ steps.tag_name.outputs.tag_name }}'
