name: device images

on: [push, pull_request, workflow_dispatch]

jobs:
  rpi4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build gnoos rpi 4 image
        run: |
          cd os/devices
          bash rpi4/build.sh

      - name: Compress
        run: xz -T $(nproc) images/gnoos.img.xz

      - name: Upload image
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: gnoos
          path: images/gnoos.img.xz

