// Code generated by genproto2. DO NOT EDIT.

package mempool

import (
	"github.com/gnolang/gno/tm2/pkg/amino"
	"bytes"
	"errors"
	"fmt"
	"io"
)

var _ io.Writer
var _ fmt.Stringer
var _ *amino.Codec
var _ bytes.Buffer
var _ = errors.New

func (goo TxMessage) MarshalBinary2(cdc *amino.Codec, w io.Writer) error {
	if len(goo.Tx) != 0 {
		if err := amino.EncodeFieldNumberAndTyp3(w, 1, amino.Typ3ByteLength); err != nil {
			return err
		}
		if err := amino.EncodeByteSlice(w, goo.Tx); err != nil {
			return err
		}
	}
	return nil
}

func (goo TxMessage) SizeBinary2(cdc *amino.Codec) int {
	var s int
	if len(goo.Tx) != 0 {
		s += 1 + amino.ByteSliceSize(goo.Tx)
	}
	return s
}

func (goo *TxMessage) UnmarshalBinary2(cdc *amino.Codec, bz []byte) error {
	var lastFieldNum uint32
	for len(bz) > 0 {
		fnum, typ3, n, err := amino.DecodeFieldNumberAndTyp3(bz)
		if err != nil {
			return err
		}
		if fnum < lastFieldNum {
			return fmt.Errorf("encountered fieldNum: %v, but we have already seen fnum: %v", fnum, lastFieldNum)
		}
		lastFieldNum = fnum
		bz = bz[n:]
		switch fnum {
		case 1:
			v, n, err := amino.DecodeByteSlice(bz)
			if err != nil {
				return err
			}
			bz = bz[n:]
			if len(v) == 0 {
				goo.Tx = nil
			} else {
				goo.Tx = v
			}
		default:
			n, err = amino.SkipField(bz, typ3)
			if err != nil {
				return err
			}
			bz = bz[n:]
		}
	}
	return nil
}

